<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>S10_Main_Part 26-TC150-156.1</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>f29751c3-8bca-4728-9089-a897be023ec0</testSuiteGuid>
   <testCaseLink>
      <guid>243b6215-9ef7-4b51-a69e-2f5e02582a62</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 10/S10_TC150-DC Inbound</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07c47d6d-230a-4bce-81a1-311c4402cc65</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ae0e1ac-283a-40fd-a895-c6f0d8ce8bfd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50973d4a-64e7-4cdc-8aae-7ead7e94c4ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ba4ee94-c49c-45fa-95fc-d7b7bfab367c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03b2ef99-2917-4e61-80a4-f27f01ccdfbb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ebc50d3-5d6a-456d-bc6a-3714b4f3f106</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>70152528-2759-4447-8e56-cdb5c2812f86</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 10/S10_TC151-Supplier1 Release Seller GI Invoice</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>255bc4d0-c5b8-4708-80ae-31269411c86f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b25e54a0-2f42-4211-8b8d-ad23fdbcddd8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7a40617b-c146-46b2-86de-68b11202b47c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 10/S10_TC152-Supplier2 Release Seller GI Invoice</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8a68da1-0665-4f93-86a7-240d93ab992b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c15211d-ecc4-49c7-ae69-a9c841e13b31</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6ab1a72e-f79e-45e0-a8d7-36f2183e2587</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 10/S10_TC153-BU Auto Generate Buyer GR Invoice</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e694faa8-2a63-4ede-b986-c61652e333d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c45cad5-370d-4a9c-8c42-49236068ede8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d9ce72ef-8e75-4317-aa5c-000ca4bd0c59</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 10/S10_TC154-BU Upload Customer Stock</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4d3b7a4-478a-4071-9994-eb6295b41a19</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>252eaae8-71ca-4b9e-8d10-a8c6aac44eac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e778100-da71-499c-987f-bf9b0845e604</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60092fe8-5295-4d83-8850-e8f1d611870c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46613c91-6171-4d69-9c31-3c5a7f091e4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46040ea8-4aa1-4381-acf0-3d544f4f68b4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>541274af-d221-4f37-b142-3e58f6f2ed79</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 10/S10_TC155-BU Upload Stock Adjustment List</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5fe0df52-f089-42f7-a4c1-70af15722826</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c2c50210-6e24-4916-9212-5f556cafe04d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f534dc4a-8974-4adc-95a3-5ae92e2c8c3a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc16b7f2-a702-43c6-ab92-09c7b27fb689</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6d2b16e-b792-46b2-897c-5065ab794e55</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>10cb6901-6dcf-46bf-9f48-0f4f9afc65f9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 10/S10_TC156-BU Check Stock History</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2bfaf3e4-1e2d-4258-a6d1-cc42802b27cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d0e96d0-2d6a-4aec-841b-4a4f96d2d70b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6bab83aa-3c71-4fa4-b6c5-01b029663b66</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 10/S10_TC156.1-Run LCBM Sync SMT Batch</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bbb8cc23-61e1-4077-967c-b7f9450a5139</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
