<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>S10_Main_Part 11-TC58-69</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>979d0b48-63a1-4d66-ac6e-1a27d74c61b4</testSuiteGuid>
   <testCaseLink>
      <guid>67affbab-9cf2-4325-bf06-9dababddf686</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 10/S10_TC058-Customer Request to modify parts</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc6b560b-6474-44e3-b57d-c07f39fd5c41</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>906f9903-1c72-4d77-982d-28ff3599680f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>179725a9-0645-4a82-9f64-58bcfc209e59</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>774cdd75-3a5c-4808-91c2-52b6991ceba3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c8231e22-c6b7-473f-bbf5-9af59b897036</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 10/S10_TC059-BU Request to modify parts</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6012497-dfc1-4047-8dcd-add699ed6d5f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2e755cc-5166-42ee-bcf2-a40409b4d811</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8995b1a8-4be6-49cb-aedc-418850da00c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d5cdfd8-d5fd-456f-a497-2ea583ccc3d6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9cdde3ce-bb25-416e-82f5-891fd53c6fbe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 10/S10_TC060-Supp1 Complete Received Request to modify parts</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9cdb8912-c22d-4c99-9141-bee5eaf81e0a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>774cdd75-3a5c-4808-91c2-52b6991ceba3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>acf9ce28-2e52-4620-818f-fd7f73b42340</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e3a86d75-6704-4643-b6eb-ec4b98dea637</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 10/S10_TC061-Supp1 Request to modify price</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1fd2d27-c531-4b26-bce3-9026884dfee1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07a6a432-a2f4-4ea1-9672-32455b7f0821</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>21b5816a-c99f-4899-b8a0-7509b2abdb15</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c89740f0-f482-42fe-b7d5-746c1e632a5f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dc16e3d1-c7ca-433a-ac00-543123a76204</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 10/S10_TC062-BU Complete Received Request to modify price</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc3df882-c0ae-4d38-b5fa-2cf1d7b8be81</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2dd8f6ba-4417-49fc-a4fa-e96181bceea3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3f0160a-3549-4e5b-b2b7-ec0aa0f057ee</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6c23598c-1a7e-49fa-aeda-00691ad596ba</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 10/S10_TC063-BU Request to modify price</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d69aeed4-75f9-4722-9f80-739b40ca06ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fbee7c60-752e-4143-995c-99f105973fff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c3f59d7-09d0-4a0d-831c-55085f29bc27</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8e7dd33-5d72-412e-a6b7-09b155494d8d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d27b6fae-701b-436b-9127-85926df7a86d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 10/S10_TC064-customer Rejected Received Request to modify price</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>87c07250-81f4-4e48-a09f-71b3ace06ae3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>74bac2ad-4af5-4fae-a1ff-fc91fcf10874</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb58062c-0b41-4b15-bf9d-dbb9713a10bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8f53968-b753-4c74-b905-6cf71e3c57aa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4a3ff782-4c1d-4acf-98d9-f1d392acda11</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 10/S10_TC065-Customer Request Remove Part</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fbee7c60-752e-4143-995c-99f105973fff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c3f59d7-09d0-4a0d-831c-55085f29bc27</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8eb9b985-01a1-4360-958d-7f82a042d9c1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6b0025e3-2587-4848-91f0-df1dca6f1f82</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 10/S10_TC066-BU Complete Received Request to remove part</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d67c67dc-46cd-434d-a16c-f3e06dcd906f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3485dc39-43f3-4a0c-8f79-440232933a85</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>010c1c18-530a-4f98-922c-9d7d37bcc79e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f7ff6209-dcff-4082-9935-a5d702247601</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 10/S10_TC066.1-BU Check remove part in Contract L3</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dcbc2553-6231-410b-8311-7ba74e88bd2a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9945813-88fc-4abc-ba1a-a3aa2393c03d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7c247b11-e17c-4b60-a57c-afc2ab5f80ef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 10/S10_TC067-BU Request Remove Part</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e5ef67a1-87ff-4f90-82d1-de54430ce750</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e3c7b7c-4b0a-4e5a-97ce-dbb696213199</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ad235ef-fceb-4ba7-8bec-17253c1465e1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ff5020de-3cc6-46ff-b889-00fc2dcfae8d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 10/S10_TC068-Supp2 Complete Received Request to remove part</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e3c7b7c-4b0a-4e5a-97ce-dbb696213199</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ad235ef-fceb-4ba7-8bec-17253c1465e1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71ee9e66-6f73-44b6-bc4c-6389bc391882</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bda84bd1-d41b-41b3-962c-f960d3f9004a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 10/S10_TC069-Supp2 Check remove part in Contract L3</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c897fc3-3e41-485b-abab-1f5813f6011b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f044699-09c6-4d7a-b9e4-fc54a5c3c85f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0bbf96d-ba37-44b9-b42d-2f332f34e9e7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f406cb61-8217-446d-99e6-1b327148839c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
