<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>S10_Main_Part 18-TC105-109</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>1c08d407-02aa-4ac7-9b88-338753c2f333</testSuiteGuid>
   <testCaseLink>
      <guid>1d0a23ba-d96c-4d7d-b877-f06bae24646f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 10/S10_TC105-BU Check Cargo Tracking Detail/S10_TC105 - BU Check Cargo Tracking Detail (run this only)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac3968e3-687f-435c-b45f-1a4df5e52b4e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ccaa16a6-b4bb-4f7f-964a-0c601c716d81</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6b69262-1c2d-49fb-82e5-6fa0cb1d5121</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>537b1e5a-c3ee-4595-a3ed-1ef80cb7edcd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9f6bc9e-833c-46b6-b350-b847de87e41d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c29f3429-1532-4856-99bc-0e90794a1474</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>75d171d0-75ca-4b5e-b16d-01b2b539ba66</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 10/S10_TC106 Supp1 Check Cargo Tracking Detail/S10_TC106 - Supp1 Check Cargo Tracking Detail</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a23a11c-ce08-4a53-a226-a34675b0b38b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5eb92055-9366-4a17-a28c-a8a5b6d55c12</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2feb7a7c-5229-43a3-98ce-7244a0ac047c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9080d1b-cb38-45ac-8de7-301db6b67dbe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30a0cb95-3691-41ee-958d-2e0f063cc7d6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38faefae-d361-42df-b4a0-85a6291c613b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>83922ef9-a759-47ea-ac1e-bfc956acc181</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 10/S10_TC107 - Sup1 AutoGenerate Shipping Detail</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd9f2978-0a78-4e39-b2a5-b0182f02eb19</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1062c224-59aa-4ed5-8ab9-2803f1fe81c8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>91900b32-ee3f-4553-8b44-422b221a4c93</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 10/S10_TC108 - BU Check Shipping Detail</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8e74ffa-60e0-47a1-8681-e3eb913d0808</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2f53b41-6670-4372-86ee-20b54a77f07b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9f4af976-9a4e-46e7-98fb-7db42d24ddc7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 10/S10_TC109 - DC Check Shipping Detail</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0ca1e7f-1de9-400e-b14a-ee7983f29d81</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7a9cee7-e511-4b07-b103-58f1380cd838</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
