<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>S10_Main_Part 15-TC141-150</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>52ff84b1-fc66-49c6-b02b-80e21d14b65d</testSuiteGuid>
   <testCaseLink>
      <guid>1ce3c42a-5c8f-43a9-af97-73199cbdcf33</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 10/S10_TC142 - BU Check Cargo Tracking Detail -SY</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bea605dd-3b12-4e35-b278-ff70f1df296c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da6ea7de-1078-478c-8d47-a2127d7c17db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51bfef0d-761a-4bfe-b677-9709a1768a08</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a18dfd6c-6b8d-4b79-b5f0-ab63afc74b66</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>862a72e4-7f79-45c8-ae6f-136fcf7da563</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a924f8b9-3218-49ba-9a3f-238d9cf159d7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>77fa8b84-164c-482e-8243-9913871fd60e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 10/S10_TC143 - Supp1 Check Cargo Tracking Detail</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec59c006-d18c-4398-870d-ff120965fa07</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f70409a3-584f-4590-8a24-d7114ca0960b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>634b3efc-5ad8-4bad-acc3-1b9bd54b43d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc567558-5b51-403d-ad9b-97598bdc13ab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83cc4e88-b029-4ced-8eae-87cb389af630</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d125d6b7-0acb-48c8-86f1-eed491a80e8e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c4f1b461-fc9a-47ae-a43c-c1b9dfcfbfd0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 10/S10_TC144 - Supp2 Check Cargo Tracking Detail - SY</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>261a66e1-4beb-42d8-9c15-481a161c4587</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>52e70474-becf-4e5f-b5ff-0c8866766a2b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b041425-a681-4de3-ab76-149792c443e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35bbe3f8-7e71-4406-b577-0ec091fcdd2d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a56fe12-fdca-42f1-bfa6-2f0d1cf344ed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf10e973-2415-4945-bfc1-345796256601</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>434297d2-8197-4e92-97cd-a86d98c48f26</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 10/S10_TC145-BU Complete Custom Invoice -Import</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e109d7c5-466e-412e-96db-0495dd5dfb2f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2fc7a775-212d-4ef8-aa64-7bcbec5ac4ab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>899c5bb3-7172-49fc-9bb7-a06380a381e9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>31bcf9ba-d3f6-4585-bd37-1fcf89ae1c33</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e37cc9fe-d2bf-4e08-be97-10c6bcefa0c6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>953003da-e68d-481c-878a-e41b050bacef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 10/S10_TC147 - BU Check Cargo Tracking Detail -SY</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf11c1df-2ba7-42bb-8e8d-46ca8661891a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e097724-24b3-4ab3-ae27-e1046f6cd93c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>78f5fe5f-6554-4341-9d74-23c9811cf435</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7aeef23c-9762-4802-a57b-53d0dbd05c8f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0277da5c-185b-4d6e-bf9e-4b01ada85fb2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>317dbcfb-0181-4f6b-86c8-cf5dc0b2029a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>12ad5d6d-695e-450e-970c-fc19b1b1a3d6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 10/S10_TC148 - Supp1 Check Cargo Tracking Detail - SY</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c075c434-38b3-4ef3-9045-e231fb34ca1a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55023e38-8c67-4c8a-beb3-19a3b62e9b26</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6635d3ce-8c71-4600-9146-4474900c9b91</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4d86c4b-23ce-4af9-b821-7887ec072a93</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3bbce7f8-1168-4cde-aa90-c1e82c713d75</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f6aeac0-a06f-4720-b2a4-d48b0d394fd5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b651f1f1-267f-4cb9-b324-16c202365be0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 10/S10_TC149 - Supp2 Check Cargo Tracking Detail - SY</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f3a82526-ef75-44ff-80c6-5c20b95a2240</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>561474e8-4a93-4c5e-bc62-52b191d11a99</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24f76127-2801-4cb8-9455-65cef98111ba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d766f2d8-6f56-464d-a0c0-3d116ede7f6e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a9dba17-22dc-4c93-8309-795363d12572</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d737bbeb-bd97-4cc7-af19-e09dade5d36d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8c54e4b6-1428-4108-b944-736170210504</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 10/S10_TC150-DC Inbound</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07c47d6d-230a-4bce-81a1-311c4402cc65</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ae0e1ac-283a-40fd-a895-c6f0d8ce8bfd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50973d4a-64e7-4cdc-8aae-7ead7e94c4ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ba4ee94-c49c-45fa-95fc-d7b7bfab367c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03b2ef99-2917-4e61-80a4-f27f01ccdfbb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ebc50d3-5d6a-456d-bc6a-3714b4f3f106</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
