<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>S10_Main_Part 19 TC171-180</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>582a3580-98b0-4853-8123-c4bb5214b721</testSuiteGuid>
   <testCaseLink>
      <guid>35d3172a-25be-4fc4-963f-ee4c812d52af</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Scenario 10/S10_TC171-Auto Generate Shipping Detail (Customer) - v2</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bb1fe577-8cf0-4345-9210-349a50b8f595</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb48d507-df1f-4728-acd7-e4055a7d04d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68fec99b-f9f8-4ec5-96d5-dd9b12aba6f6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c9f852b-7456-4d99-b505-08a44df97f81</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc06ce30-473b-4d9f-bd1a-37d781a7efb6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d75b39c7-6ef0-46c4-b3df-38bb9b5a92b3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>20d37fb0-a4dc-4927-8d38-8597529ec54c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4095ab4-750b-4692-afde-2fa4b2e758da</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>268e6448-f187-4f70-b2dc-a7d61c73ffbe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Scenario 10/S10_TC172-BU Auto Generate Seller GI Invoice</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff406a63-950e-4fc1-8ce5-b83d4e2124c5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>25e8f95b-4810-42db-9577-d892a20f4abe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Scenario 10/S10_TC173-BU Approve Seller GI Invoice</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51f7b766-44a0-47cd-8e8d-02f58c492a8f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>50ae4ab5-bf96-4bf2-90a6-13ffc2cd76a5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Scenario 10/S10_TC174-BU Release Seller GI Invoice</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3edfb01d-424f-4a7f-b312-295732f8fa31</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1904959b-dd79-48b2-97a9-0cc98b544cb9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Scenario 10/S10_TC175-Customer Auto Generate Buyer GR Invoice</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d47b3a6-c48a-46bc-a422-6bb1508d71f2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>26121467-3bce-4964-a702-a4adf0ba8b28</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Scenario 10/S10_TC176-Customer Inbound L2 Parts</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>661f7474-b48d-465e-903a-40d9ee467e63</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca4ef335-fcb7-4be0-82bd-7982eaeaa70f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9813a994-89fb-41ef-9c76-b240749fdc3c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb830c37-a229-4299-be01-96d2a68b8acd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f382175b-9800-43e0-bcf9-d37faf83c542</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>58543c6c-95b9-446f-8851-9abefed187e8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>22970889-174d-44c8-8d2f-57a1de94034f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Scenario 10/S10_TC177-Customer Check Customer Order</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ecd1df09-d390-46d3-aea4-7ecb20d954bb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>592bc4b5-ff6f-486e-a24c-670532f457e8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Scenario 10/S10_TC178-BU Check Sales Order</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67362e85-b937-404d-8c04-c31d0fa4d8bd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b6869657-284e-411a-8faf-14614a2d2cb5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Scenario 10/S10_TC179-Customer Update Shipping Detail</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c0861f9-b27a-413d-8aa9-d8bdf51f19ce</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>051688af-e992-4fa5-ae75-cefce41fe598</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 10/S10_TC180-BU Check Shipping Detail</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f8c1be7-d8d3-4cba-aaf7-3dbd4b6e55e8</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
