<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_UploadFile</name>
   <tag></tag>
   <elementGuidId>b370088c-eca7-4f2b-b0e2-f4d3c928a4ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='file']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>629181af-370c-42e1-92ff-14fc683ceaf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1689163806599</value>
      <webElementGuid>3ac213cf-f7b9-4fa9-a8e0-ee45f5826a75</webElementGuid>
   </webElementProperties>
</WebElementEntity>
