<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h6_Order Number</name>
   <tag></tag>
   <elementGuidId>7a0cd1e8-f545-437e-926b-41e0001ebdd6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h6.lcbm-MuiTypography-root.lcbm-lcbm553.lcbm-MuiTypography-subtitle2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@title = '${buttonOrderNo}' and (text() = '${buttonOrderNo}' or . = '${buttonOrderNo}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h6</value>
      <webElementGuid>33719fea-0188-449f-b098-1b86563a775d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lcbm-MuiTypography-root lcbm-lcbm553 lcbm-MuiTypography-subtitle2</value>
      <webElementGuid>52b83748-7021-448c-bd36-de09669745e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>mui-8854</value>
      <webElementGuid>bbc25ab6-35a2-4b6c-a2c3-aaa1930ca7bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Order Number: cFT03-2308001</value>
      <webElementGuid>86d07852-fbd4-4afe-8899-5032f4984d74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;webapp-lcbm&quot;)/div[@class=&quot;os-host os-host-foreign os-theme-dark os-host-resize-disabled os-host-scrollbar-horizontal-hidden lcbm-lcbm187 os-host-transition os-host-overflow os-host-overflow-y&quot;]/div[@class=&quot;os-padding&quot;]/div[@class=&quot;os-viewport os-viewport-native-scrollbars-invisible&quot;]/div[@class=&quot;os-content&quot;]/div[@class=&quot;lcbm-lcbm188&quot;]/div[@class=&quot;lcbm-lcbm193&quot;]/div[@class=&quot;lcbm-MuiPaper-root lcbm-MuiCard-root lcbm-lcbm195 lcbm-MuiPaper-elevation3 lcbm-MuiPaper-rounded&quot;]/div[@class=&quot;lcbm-MuiCollapse-root lcbm-MuiCollapse-entered&quot;]/div[@class=&quot;lcbm-MuiCollapse-wrapper&quot;]/div[@class=&quot;lcbm-MuiCollapse-wrapperInner&quot;]/div[@class=&quot;lcbm-lcbm198&quot;]/div[@class=&quot;lcbm-lcbm549&quot;]/div[@class=&quot;lcbm-MuiPaper-root lcbm-MuiCard-root lcbm-lcbm550 lcbm-MuiPaper-elevation20 lcbm-MuiPaper-rounded&quot;]/div[@class=&quot;lcbm-MuiCardContent-root lcbm-lcbm551&quot;]/div[@class=&quot;lcbm-MuiGrid-root lcbm-MuiGrid-container lcbm-MuiGrid-direction-xs-column-reverse lcbm-MuiGrid-align-items-xs-center lcbm-MuiGrid-align-content-xs-center&quot;]/div[@class=&quot;lcbm-MuiGrid-root lcbm-MuiGrid-item&quot;]/h6[@class=&quot;lcbm-MuiTypography-root lcbm-lcbm553 lcbm-MuiTypography-subtitle2&quot;]</value>
      <webElementGuid>e8f2360c-9c90-4331-9f8b-d948c7ad5f9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='webapp-lcbm']/div/div[4]/div/div/div/div[2]/div[3]/div[2]/div/div/div/div/div/div/div/div/h6</value>
      <webElementGuid>072c8b96-879e-4356-aae2-b668b4ebeec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Order/s To Retrieve Cargo Tracking Information'])[1]/following::h6[1]</value>
      <webElementGuid>a796c7a5-0622-444e-af0b-7b7936e890fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::h6[2]</value>
      <webElementGuid>aa72c44f-3290-47e4-94f4-8295d66a2108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Booking Number: B-230816-FT-01-003    Container Number:'])[1]/preceding::h6[1]</value>
      <webElementGuid>cddf6778-0604-4732-a38c-4acb61cc812d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)=':']/parent::*</value>
      <webElementGuid>7ca265c0-d922-431b-8f70-545a6cc930cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div/h6</value>
      <webElementGuid>22059af8-2a45-4af4-9656-f65a46353854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h6[(text() = 'Order Number: cFT03-2308001' or . = 'Order Number: cFT03-2308001')]</value>
      <webElementGuid>665c2383-46ac-44e7-a2b3-2c89d94b9863</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
