<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_expAgencyUidOption</name>
   <tag></tag>
   <elementGuidId>c1341080-ff0d-471b-8b9f-381ebf357393</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-51722-option-6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='mui-51722-option-6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>6dbcb9ef-0d3c-4537-a3bc-d3d2fb476b05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>dd13def8-48a0-4dd1-9f99-3e972f26a0a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>6d04f05e-80b1-4e51-9903-3a74e2ee0857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-51722-option-6</value>
      <webElementGuid>42969eba-bd41-4c5f-807b-110042b59f9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>11603417-0a97-4ea1-85b4-03a46accb48c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>361e3492-1dab-4384-b2fa-23f7b38b96bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8ad7a744-464a-4e30-b36e-6285b722b84d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lcbm-MuiAutocomplete-option</value>
      <webElementGuid>9c97ee4e-bc05-4610-bb99-3cb4f9532129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focus</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>721d9011-17f0-4e5d-96bc-61808b9b29e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${expCustomParty}</value>
      <webElementGuid>e4df16ce-21a5-48ac-b38b-df068a474932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-51722-option-6&quot;)</value>
      <webElementGuid>ad02bb92-0833-46c4-adf9-5646375cd061</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='mui-51722-option-6']</value>
      <webElementGuid>dee368cc-b6a6-4b82-a5f6-354e91ac9848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='mui-51722-popup']/li[7]</value>
      <webElementGuid>887cde78-781b-4149-96f4-fb3e5d2fd3a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CNTW-SUP-001'])[1]/following::li[1]</value>
      <webElementGuid>ca5098a5-ed69-4753-b6be-3ee36f5aa2c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CN-NIN-SUP'])[1]/following::li[2]</value>
      <webElementGuid>c4e80384-859e-46c0-b322-25d2f435e8de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CUS-001'])[1]/preceding::li[1]</value>
      <webElementGuid>664ed66b-7f82-438b-affa-a0ac640d270a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CUS-004'])[1]/preceding::li[2]</value>
      <webElementGuid>ea038e31-0dbb-49e3-9e78-d203fdfc24ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CNTW-SUP-POC']/parent::*</value>
      <webElementGuid>ba5dc695-d41c-445b-89f8-06b515a13202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]</value>
      <webElementGuid>d25d6c96-e314-4232-a720-9b508a744150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'mui-51722-option-6' and (text() = 'CNTW-SUP-POC' or . = 'CNTW-SUP-POC')]</value>
      <webElementGuid>0fbafd2c-44fe-4266-8913-c746d4cc9e98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
