<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h6_Download Outbound Delivery Plan</name>
   <tag></tag>
   <elementGuidId>51538a7b-dcaf-4038-8ad0-8470281c2e68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h6.base-MuiTypography-root.base-base163.base-MuiTypography-subtitle1.base-MuiTypography-noWrap</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='webapp-base']/div[2]/div/div/div/h6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h6</value>
      <webElementGuid>01da1e44-5183-4ff5-bc7b-220e11c49711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>base-MuiTypography-root base-base163 base-MuiTypography-subtitle1 base-MuiTypography-noWrap</value>
      <webElementGuid>825f8c2f-fa3c-4e2d-99cc-de4fa32b6029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>mui-11711</value>
      <webElementGuid>c1c9b00a-86a1-4293-9188-2d70717bba11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Download Outbound Delivery Plan.</value>
      <webElementGuid>546f600f-68b9-4fd4-b028-a19da0d85fb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;webapp-base&quot;)/div[@class=&quot;base-base1 base-base3 base-base5&quot;]/div[@class=&quot;base-MuiPaper-root base-MuiAlert-root base-MuiAlert-standardSuccess base-base161 base-MuiPaper-elevation0&quot;]/div[@class=&quot;base-MuiAlert-message&quot;]/div[@class=&quot;base-base162&quot;]/h6[@class=&quot;base-MuiTypography-root base-base163 base-MuiTypography-subtitle1 base-MuiTypography-noWrap&quot;]</value>
      <webElementGuid>fefd8b57-37ed-4c80-94df-a520f9700ab1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='webapp-base']/div[2]/div/div/div/h6</value>
      <webElementGuid>7b555b5f-106c-4349-a99b-c1c05aef4850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='a'])[1]/following::h6[1]</value>
      <webElementGuid>a246f50f-00a8-4c0b-a986-f667440005e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privilege'])[1]/following::h6[1]</value>
      <webElementGuid>82e174d7-e488-424f-b5cc-0e46c85252b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/preceding::h6[1]</value>
      <webElementGuid>140c111a-eb57-4934-9bba-3f0c4585ea28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download Outbound Delivery Plan.'])[2]/preceding::h6[1]</value>
      <webElementGuid>e43e7fa4-13d7-4682-a779-6918b41d266b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Download Outbound Delivery Plan.']/parent::*</value>
      <webElementGuid>00c1334d-4637-48fc-a47f-0cde5bafc2ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/h6</value>
      <webElementGuid>a84a59c4-1f2c-418a-90ed-75c19d457457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h6[(text() = 'Download Outbound Delivery Plan.' or . = 'Download Outbound Delivery Plan.')]</value>
      <webElementGuid>0fc1e633-da47-4e7b-ba82-d6c4b20beb3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
