<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SalesOrderNo</name>
   <tag></tag>
   <elementGuidId>92954693-82e0-4266-9b7d-739c5e93b96c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;orderNo&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='orderNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b4821744-35b4-4602-a797-e9f08f8b7ab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>orderNo</value>
      <webElementGuid>5edfac09-e9e5-45e9-98e9-b038ea76b345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1dc92b20-82e3-455c-a0f2-c46a1b9fc909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lcbm-MuiInputBase-input lcbm-MuiInput-input</value>
      <webElementGuid>68bd9b5d-1068-4797-96c3-9c0ea77a0714</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>sCP1-2307001</value>
      <webElementGuid>a2e1cb95-4d51-4224-b9cc-45e42d926035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OSS011_Section_1&quot;)/div[@class=&quot;lcbm-MuiCollapse-root lcbm-MuiCollapse-entered&quot;]/div[@class=&quot;lcbm-MuiCollapse-wrapper&quot;]/div[@class=&quot;lcbm-MuiCollapse-wrapperInner&quot;]/div[@class=&quot;lcbm-lcbm914&quot;]/form[@class=&quot;lcbm-lcbm2578 lcbm-lcbm2617&quot;]/div[@class=&quot;lcbm-lcbm2580 lcbm-lcbm2618&quot;]/div[@class=&quot;lcbm-lcbm2582&quot;]/div[@class=&quot;lcbm-lcbm2589&quot;]/div[@class=&quot;lcbm-lcbm2595 lcbm-lcbm2600&quot;]/div[@class=&quot;lcbm-lcbm2584&quot;]/div[@class=&quot;lcbm-MuiInputBase-root lcbm-MuiInput-root&quot;]/input[@class=&quot;lcbm-MuiInputBase-input lcbm-MuiInput-input&quot;]</value>
      <webElementGuid>ada6c450-68be-4187-96d8-ae191935a436</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='orderNo']</value>
      <webElementGuid>6e0d6f31-17c4-476b-a9a7-394f7e564b33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='OSS011_Section_1']/div[2]/div/div/div/form/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>9ba168cc-3547-4676-8c88-29b2de0e7f37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>43c949d4-da0f-4fc5-a999-c2d347996c56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'orderNo' and @type = 'text']</value>
      <webElementGuid>fef86248-7c1d-4e77-9e3f-25737d3de0c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
