<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_regioncode</name>
   <tag></tag>
   <elementGuidId>e628486f-2212-4490-b203-f5ca48c97353</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-20579-option-9</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '${RegionCode}' or . = '${RegionCode}')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='mui-20579-option-9']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>e2a9be03-8bc8-45c0-9480-be200171f5c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>08b35576-9642-4c90-81fc-7a078b593f87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>d31877eb-2776-4fec-b958-01ab192253d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-20579-option-9</value>
      <webElementGuid>037deb7b-01c2-4c6c-9b92-59f3a92d260e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>0b7a256a-1515-401d-ac24-2303ee552116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>befa0ed4-b446-4913-8ac0-6742c7e65c8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ee42f908-c5ab-4954-a0e9-8d803e6f659c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lcbm-MuiAutocomplete-option</value>
      <webElementGuid>9470b725-e52e-4a7a-bcca-5e55dba01031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focus</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7d541bcd-2759-4251-9405-345cebe10e98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${RegionCode}</value>
      <webElementGuid>d2ef2bea-4047-412b-9461-cfa5e38583e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-20579-option-9&quot;)</value>
      <webElementGuid>70759883-a533-4712-a54f-b2398c36d74b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='mui-20579-option-9']</value>
      <webElementGuid>c1d7afbd-a76d-4cc8-b209-81d0668163c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='mui-20579-popup']/li[10]</value>
      <webElementGuid>b8391e65-f986-4b2d-91cf-24dfc726a17a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JP'])[1]/following::li[1]</value>
      <webElementGuid>bd661584-b529-4e6a-9b81-cc720523732c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IN'])[1]/following::li[2]</value>
      <webElementGuid>fcf5a64f-c24e-46fc-b8dd-2266330240f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PH'])[1]/preceding::li[1]</value>
      <webElementGuid>a5d38476-f5da-4d65-89a3-a4264c2ac5ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PK'])[1]/preceding::li[2]</value>
      <webElementGuid>4e02bc5f-9d89-4a0c-8f06-2a16de3a9565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MY']/parent::*</value>
      <webElementGuid>fe86b7b9-d93b-46c8-be07-6a2aea01fb0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[10]</value>
      <webElementGuid>7e90e50b-701d-4f4b-a187-e5c36c9da77f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'mui-20579-option-9' and (text() = 'MY' or . = 'MY')]</value>
      <webElementGuid>f9eeea6b-5cc5-489f-a53b-748c1b449b59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
