<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>S9_TC001-TC020</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>d5a78cd6-c65d-438b-9769-47eadb39fa9e</testSuiteGuid>
   <testCaseLink>
      <guid>de86511b-9dc5-4f45-9ea5-9409ac76b4ca</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Scenario 9/S9_TC001-Customer Request Add New Part</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>77a62d93-082a-4a91-a2ce-974fdbeb0e67</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>27699e28-6aa6-4fce-a45c-e9e1e3067466</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1adb8cfc-5c36-482d-a38d-07c353bc7729</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>840a5740-8c26-44d0-a91d-525c4d08c057</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>77d2d81a-df1c-4c74-b939-eb96db27a488</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4fd28ad6-3f0f-4f69-ab55-be15ac3eb406</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>717fedde-98a0-471f-b4b9-0bbf1494b1b5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Scenario 9/S9_TC002-BU Received Request List</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d507a8f-aa8d-46e9-88de-8e30480f0077</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>224450ed-5b6a-4dfd-b90e-a600b1da1e19</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c06e756c-fba1-4dd5-b3d6-3c1e2ddf2f00</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f107132-de9a-4897-a39a-435354b25604</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc6e806a-f423-4b02-95d1-b914e32aec13</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18a29074-ab9c-485e-8738-3d77669d422c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c7b875c-7608-464e-82e8-91fdc987023a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1ff9e1f-4c9a-4ad8-b903-291b9557befb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebb347d4-65db-4047-8be3-f94edf4bf959</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85d7ed14-0ade-4934-83cf-cdc1862cfda9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b7762bb-ca2c-4dcd-b567-eaf57935437b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75349cf1-c9e2-4857-acdd-251624559c03</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c5c4c39-8d15-4902-85a6-e50055246eaf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bbde3d3f-aa77-48a4-ae45-911d5ffff7c7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a236002f-9d64-4158-b4b7-4c039c0a3842</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a214ca6-319e-43b3-8fdc-d6314befc759</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b7ab3afe-efb6-4bf1-81aa-5bd55c55b971</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9aed7598-9260-441f-9aef-d902e82411cf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>105da8dd-0ad8-43d0-89ca-b75c2e96ec78</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a47d2186-a310-48e2-8680-829e358ef81e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Scenario 9/S9_TC003-BU Auto Generate Contract Route</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>099d2e69-013b-4417-a864-2ea3e4ea0508</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>514fde03-bd12-4a39-83b3-0cd2369b8dbe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c81ae305-92ac-448a-9e89-29183a532467</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>388a436b-2bb6-44a8-9a85-b663552f4e9b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2f0ab1ab-eb5e-4fcf-8728-6ede453788be</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Scenario 9/S9_TC004-Supplier Received Request List</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f35626b9-1f2c-4899-9cfc-bf323848368c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>258cb30d-7f63-40cf-b5fe-c158ed76ad57</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6da0a141-e7b3-45a5-9cb5-5e399bba07de</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7da59002-da2c-443c-bf88-b4fe3ed79d74</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>37406beb-eb53-4ec3-8b5a-abc2de05338a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>032a729f-7657-49d3-8973-daaad03f782e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a4be70a-c1b1-4188-be1c-f7e4066bdc02</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28b2627c-8e65-46b4-9f70-14423755f09e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ecbc2b02-ff8d-4c6d-af75-cfd5c32aaefd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fdc4491c-4726-4dc1-9615-82842b142a43</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a0b6a01-eb15-4742-b075-0573c2d7a00c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd0b6081-ad7a-4ebf-96d0-b42d415695b1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e14edda-6bcb-428c-a937-4c4c22ef434b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8a4a643-4b49-4a25-901c-acadd8b36b79</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e25432ac-2b41-451d-92ff-611039f064cf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d36b493-6147-43f2-938d-ed43ef9e467a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0ee1f7de-23de-4aaf-88a6-ac551fecd7d7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Scenario 9/S9_TC005-BU Check Contract Route</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4b1ddad-8734-4d2f-b687-525dbd2d9c8a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>630cb93e-04b7-4380-8e8b-bae7b9439b36</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ec7c760-d7f3-40b9-bfe4-8bee8dc0adc2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ed02348-2d3a-4be5-a84e-b4566acb3ede</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d70fe2f-1a6f-4fbb-a02f-b4c7e1a3ae2c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fd1cced6-af62-4cc5-a649-dbaba92bb271</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Scenario 9/S9_TC006-Supplier Check Contract Route</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb5353ac-5f3c-488e-ba33-752854128e0e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c71294c-863b-4c83-9375-99af1db1fa62</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0f7566f-a788-4103-aabf-6faca75a8c7c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8231caf-9a33-40b0-8121-7e8b92a672b1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>619c555b-3b07-4a5f-9d18-460bf53de3a3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>920233c2-6514-4c3b-88fb-2cb231bf9d52</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 9/S9_TC007-Supplier Release Received Request -Not Delete Contract</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8a5a9e4-2a1e-46ca-8386-8d7398b350b4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b0a15c86-4c76-44c6-a427-e81fa3e0e41d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Scenario 9/S9_TC008-BU Check Request List</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9577cd90-4ae4-4419-9a2a-07723eb0526c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bbe87195-64ec-4147-95df-c38230feb682</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Scenario 9/S9_TC009-BU Check Contract Route</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e603660b-d805-4ddb-a015-69d3ce787e44</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a1dda27-351c-48e0-ad61-d0367af6fc62</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3cb6d7f7-c3cc-4868-be6c-22bdb8a389df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6e9e94f-2ea4-4296-90ba-d016fc96a2f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48d2cd0f-8091-4c64-8ee0-3cd11a1764f5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4d3aa59a-1949-4978-ad13-330076343c2c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Scenario 9/S9_TC010-Supplier Check Contract Route</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01479359-8d52-4511-9a3c-820f776604a5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3c579700-f162-4d75-91aa-91162beda08f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 9/S9_TC011-Supplier Reject Received Request</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d62b7e0-7cd7-4637-8f62-4af7e35f12af</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>796dddc0-fc10-4d48-bcb1-0c15b8afe843</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Scenario 9/S9_TC012-BU Check Request List</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>804c2001-aecd-4670-b42f-71a3b1b1181a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fb96eb35-ed8c-4080-a6f6-35b8ad5109dc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 9/S9_TC013-BU Release Received Request -Not Delete Contract</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>37a7b0ae-10b9-49cb-bebe-02a2922cb6af</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d946c012-3d20-475b-b931-4cc43488d3cf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Scenario 9/S9_TC014-BU Check Request List</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f93d89a1-d5ca-44e5-ae7a-158ae7b34b26</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0086459a-6c5b-4fda-8308-2ccd23058692</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Scenario 9/S9_TC015-BU Check Contract Route</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0df75ec9-2bef-46da-8104-5585aeb00d5b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b1239684-05e5-4eb0-a5b3-2509af33187a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Scenario 9/S9_TC016-Customer Check Contract Route</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02b06039-3b77-45ae-91be-afca976701a7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a0355b9b-ae33-48f4-87a6-a2553f3f1448</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Scenario 9/S9_TC017-Customer Check Request List</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>443396f6-e0d0-4879-b833-171ad16b8be6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>589d9223-c559-44b6-a972-b396346f2046</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 9/S9_TC018-BU Reject Received Request</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a36f8fd-b335-4d63-a948-317f79c350c2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ebebb48b-8091-4d02-a2a0-b8bffb7fc4cb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Scenario 9/S9_TC019-Customer Check Request List</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5f97300-bee5-45db-9a51-30dff96a905e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>942673cf-0595-4576-8312-7402fe84c5d1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 9/S9_TC020-Customer Submit Request Reject</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a65ea6fe-b495-4938-954b-17a9925f13f4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>74046bc0-8a74-4574-a283-fc4c6893663c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e1ab585-7ac2-4f39-8531-947c953e0d28</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f66acd50-4e9f-4b77-8739-8fa5f1f6b2ac</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
