<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_defaultCompanyTarget</name>
   <tag></tag>
   <elementGuidId>d94b13a2-a010-4d01-8ab2-0d58745442ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-44598-option-0</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '${defaultCompany}' or . = '${defaultCompany}')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[(text() = '${defaultComp})' or . = '${defaultComp}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>66eaccc5-4e06-4af6-bc8e-7b0f0855bf08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d6b19abc-3a56-4773-b288-bea3c0ab92ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>be691f03-5e18-4512-b577-12e9bad6be1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-44598-option-0</value>
      <webElementGuid>b7d2c143-e77a-4b42-ba5d-fda3ac378190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c015479b-78d9-4251-b37c-97f0023944a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e7f72fa8-b17b-424d-9430-641132a66a28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>10c32dc2-629b-4fb5-85b8-c68691925e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lcbm-MuiAutocomplete-option</value>
      <webElementGuid>993f44e3-9a23-45d4-a340-8f40f32a92da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focus</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>df6076d1-63f2-4d10-9df8-3459a432905b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${defaultCompany}</value>
      <webElementGuid>82a05d89-6e84-4b5e-af6c-f46764ec853b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-44598-option-0&quot;)</value>
      <webElementGuid>742bd6a8-7242-4651-8364-f31a2fed20f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='mui-44598-option-0']</value>
      <webElementGuid>b0accbeb-e2a4-42c4-bbf5-281ec54426dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='mui-44598-popup']/li</value>
      <webElementGuid>b2b34108-3902-45c4-959b-d8c916e97f15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/following::li[1]</value>
      <webElementGuid>22729034-a87d-4a2e-904f-568eb2266d59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='a'])[1]/following::li[1]</value>
      <webElementGuid>8994b914-1e97-418b-ae21-55e31b47425e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CUS-001 ( PK-CUS-001 )'])[1]/preceding::li[1]</value>
      <webElementGuid>3c8f98a6-6d66-4f5c-814f-e08215de2788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PK-CUS-POC ( PK-CUS by Upload )']/parent::*</value>
      <webElementGuid>e724cb81-d57f-489f-93b7-eee03353d7b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/li</value>
      <webElementGuid>ecd76fdd-2a6a-42c1-87d4-9054ee7a9ba8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'mui-44598-option-0' and (text() = 'PK-CUS-POC ( PK-CUS by Upload )' or . = 'PK-CUS-POC ( PK-CUS by Upload )')]</value>
      <webElementGuid>e4852ab4-0401-4474-8b5f-bb14874a009f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
