<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Options_CargoStatus</name>
   <tag></tag>
   <elementGuidId>820aab8e-d742-401e-851b-85922e108ab7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[(text() = '${statusUpdate}' or . = '${statusUpdate}')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mui-75216-option-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Gate in (Gate In to Outbound Terminal)']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>d980ee81-a0f5-41bc-9ce1-29ed1c18fcf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>b81bcd38-75c8-4f5c-8837-b7786a97c24f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>e6f9e221-a47c-4831-8d38-ba1b3698679b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-75216-option-1</value>
      <webElementGuid>24dce0de-3a99-421a-9852-8d0d79f60aa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8b43be74-7507-4fce-b762-046ec5e02f41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2faea73d-229e-4aef-be65-d579ca121695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c49a4234-a5de-42a2-8b2a-f73d08eb5264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lcbm-MuiAutocomplete-option</value>
      <webElementGuid>5f08669a-3044-4e78-8b0d-4a3b03e96ec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focus</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>916d739c-7649-4ddb-8d15-5e7c664adf0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${statusUpdate}</value>
      <webElementGuid>6f402789-3caa-46e9-9bce-738531f75a2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-75216-option-1&quot;)</value>
      <webElementGuid>16e4b012-99e7-44bd-8a90-0e03f456628c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='mui-75216-option-1']</value>
      <webElementGuid>77db0dcb-a9bf-496f-a201-8a3cf0eaba19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='mui-75216-popup']/li[2]</value>
      <webElementGuid>bdb367a2-9df3-42a9-a726-d33446b664d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Empty container pick-up (Empty Container Release to Shipper)'])[1]/following::li[1]</value>
      <webElementGuid>372e13b2-7b64-401b-a1ef-b3e905aea4ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='update'])[1]/following::li[2]</value>
      <webElementGuid>41a88282-6f63-4042-a2a3-fe6362d14893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loaded (Loaded on vessel at Port of Loading)'])[1]/preceding::li[1]</value>
      <webElementGuid>ac0f5bba-6a14-47bb-a9e1-394cfad1d9a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Departure (vessel Departure from Port of Loading)'])[1]/preceding::li[2]</value>
      <webElementGuid>cfd31015-cafd-4e02-b6d5-9ffa628b249d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Gate in (Gate In to Outbound Terminal)']/parent::*</value>
      <webElementGuid>18e8bdf2-2b9c-4992-a24d-cfefe2188c0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[2]</value>
      <webElementGuid>0b1ec7ec-23cb-4460-b2be-63bd3dec0339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'mui-75216-option-1' and (text() = 'Gate in (Gate In to Outbound Terminal)' or . = 'Gate in (Gate In to Outbound Terminal)')]</value>
      <webElementGuid>567ba749-41f7-4cc1-8188-2d6e2ea6093d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
