<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please input related basic information_status (1)</name>
   <tag></tag>
   <elementGuidId>56282611-698e-48a0-8e39-963e351ec295</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='status']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;status&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e0cfe0fb-6eb7-4641-97d6-8953d509eae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>c59339c0-39d2-4c1b-b91a-0c0b92f32046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ead1f1e0-f91d-4690-b147-0b586640bba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lcbm-MuiInputBase-input lcbm-MuiInput-input</value>
      <webElementGuid>a858ac4d-3d37-46e1-b160-9597caef4fec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Completed</value>
      <webElementGuid>9af850bd-ff92-41f7-8019-7fc68f33e1a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OSS011_Section_1&quot;)/div[@class=&quot;lcbm-MuiCollapse-root lcbm-MuiCollapse-entered&quot;]/div[@class=&quot;lcbm-MuiCollapse-wrapper&quot;]/div[@class=&quot;lcbm-MuiCollapse-wrapperInner&quot;]/div[@class=&quot;lcbm-lcbm53&quot;]/form[@class=&quot;lcbm-lcbm978 lcbm-lcbm1017&quot;]/div[@class=&quot;lcbm-lcbm980 lcbm-lcbm1020&quot;]/div[@class=&quot;lcbm-lcbm982&quot;]/div[@class=&quot;lcbm-lcbm989&quot;]/div[@class=&quot;lcbm-lcbm995 lcbm-lcbm1000&quot;]/div[@class=&quot;lcbm-lcbm984&quot;]/div[@class=&quot;lcbm-MuiInputBase-root lcbm-MuiInput-root Mui-focused Mui-focused&quot;]/input[@class=&quot;lcbm-MuiInputBase-input lcbm-MuiInput-input&quot;]</value>
      <webElementGuid>9e79bae4-d6f7-43cc-ae0d-f1f9c547ffd5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='status']</value>
      <webElementGuid>fd6fbc5d-0ec5-402f-bd8b-9d4e14f01c9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='OSS011_Section_1']/div[2]/div/div/div/form/div[3]/div/div[2]/div/div/div/input</value>
      <webElementGuid>8f8bf4c3-5f9a-4acd-84fc-6db2d51f55de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/div/input</value>
      <webElementGuid>d093aa0c-488c-494a-831e-79fe748fe045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'status' and @type = 'text']</value>
      <webElementGuid>1c408d81-15cf-42f3-bcc2-cfdc693102f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
