<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Order</name>
   <tag></tag>
   <elementGuidId>b6a5a93b-b364-4703-ab9d-0e8e58513fb4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.base-MuiButtonBase-root.base-MuiButton-root.base-MuiButton-text.base-base109</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[52]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c2094ef9-669f-4459-afad-d84c2897554a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>base-MuiButtonBase-root base-MuiButton-root base-MuiButton-text base-base109</value>
      <webElementGuid>e8a04033-4863-4339-9d88-e7649b55f088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>729dd518-f726-494a-9f28-8b6de92c2867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d7f2036b-38ad-4cd3-896b-946da2e5f1e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7d573aa5-39ca-41df-bfc5-57b5a6dc2982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Order</value>
      <webElementGuid>da0faaa4-0970-461b-b1ee-6c39c001499f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;webapp-base&quot;)/div[@class=&quot;base-base93&quot;]/div[@class=&quot;base-base94&quot;]/div[@class=&quot;base-base95&quot;]/div[@class=&quot;base-base97&quot;]/nav[@class=&quot;base-base104&quot;]/div[@class=&quot;base-base105&quot;]/div[@class=&quot;base-base106&quot;]/button[@class=&quot;base-MuiButtonBase-root base-MuiButton-root base-MuiButton-text base-base109&quot;]</value>
      <webElementGuid>058401d7-a5aa-4577-bb8e-2f0118026f49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[52]</value>
      <webElementGuid>130a899e-79b1-40da-8dbe-e6c2aec94ca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='webapp-base']/div/div/div/div/nav/div[2]/div/button</value>
      <webElementGuid>70d81591-cd49-4d9b-b859-15b92eb8bb8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You have pending master to process'])[1]/following::button[3]</value>
      <webElementGuid>e9809193-702c-4dd5-bb0d-4430d1c16dce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logistics'])[1]/preceding::button[1]</value>
      <webElementGuid>5acb2cd9-c553-473a-be8e-eab47a6d7ee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div[2]/div/button</value>
      <webElementGuid>be00d586-dd2f-47fb-8541-2b8ea299f6e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Order' or . = 'Order')]</value>
      <webElementGuid>db86dcb4-e5ce-4408-88de-0aa60f2bea85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
