<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Convert</name>
   <tag></tag>
   <elementGuidId>f805d2a7-bbbc-451d-8c3a-85ed73790c1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#runCodeButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='runCodeButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a87d3fd0-1579-4805-9e1a-a62580983877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>actionButton</value>
      <webElementGuid>a1528ae5-ed34-4878-8b8b-986d0b2c4d4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>runCodeButton</value>
      <webElementGuid>39553f17-6191-42f6-ab9b-cea32f70ee33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6f6e3bba-342d-4d46-9b8b-c437f2ffb6ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>runCode()</value>
      <webElementGuid>fab1e121-ab52-4ac6-8884-45d987e2e0ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Convert</value>
      <webElementGuid>116bc780-3ec8-4a9d-8bc0-443733ca516e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;runCodeButton&quot;)</value>
      <webElementGuid>749b8211-408f-48f8-b269-8c587fbf11a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='runCodeButton']</value>
      <webElementGuid>1ca601df-0944-45a2-abd8-9d63b87b817d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='appui']/div[2]/div/div[4]/a</value>
      <webElementGuid>94fe4197-558d-4573-adbc-b7b5aecf3595</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Convert')]</value>
      <webElementGuid>f3b9faea-23ff-46c6-917e-662193f1e5d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload a file'])[1]/following::a[1]</value>
      <webElementGuid>91f977c6-ab74-478c-9c08-4c112708c207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Input file'])[1]/following::a[1]</value>
      <webElementGuid>d3b689a9-cbc8-4884-a0c1-0cd14c28fc35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select format'])[1]/preceding::a[1]</value>
      <webElementGuid>8a2c6c03-30ad-461d-882f-f6888d5841c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Convert']/parent::*</value>
      <webElementGuid>1a9e3d01-f10d-42e5-85e8-a42ddd4eb73a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]/a</value>
      <webElementGuid>68696794-1598-4f6f-92e6-a66087f27425</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'runCodeButton' and @type = 'button' and (text() = 'Convert' or . = 'Convert')]</value>
      <webElementGuid>72d9e49d-acdb-49d6-9d2e-6746d83be2c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
