<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Stock Management Tool</name>
   <tag></tag>
   <elementGuidId>b95fa561-3985-4f0c-9f8c-fc8f954289f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[61]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>aadbe868-a871-4d7c-a102-cbf639ceb4df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>base-MuiButtonBase-root base-MuiButton-root base-MuiButton-text base-base357</value>
      <webElementGuid>a5c5f114-45a3-4318-bc34-167b6cd93f91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6ad05778-3028-4f1f-a359-f6a691001002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4d9bf39c-1eff-4f64-97d7-b66a5c19aaf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f58f162d-d89c-4e43-bc03-26222810eafd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Stock Management Tool</value>
      <webElementGuid>0125806e-8532-4768-86d4-4b530af681db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;webapp-base&quot;)/div[@class=&quot;base-base341&quot;]/div[@class=&quot;base-base342&quot;]/div[@class=&quot;base-base343&quot;]/div[@class=&quot;base-base345&quot;]/nav[@class=&quot;base-base352&quot;]/div[@class=&quot;base-base353&quot;]/div[@class=&quot;base-base354&quot;]/button[@class=&quot;base-MuiButtonBase-root base-MuiButton-root base-MuiButton-text base-base357&quot;]</value>
      <webElementGuid>90e3341e-f1e8-4a40-9c2f-cc11cced73ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[61]</value>
      <webElementGuid>ff0cedf6-eed9-4621-ac19-6fb0566fe039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='webapp-base']/div/div/div/div/nav/div[2]/div/button[8]</value>
      <webElementGuid>3c24624d-ea9d-4505-908c-ed44cbe9b615</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privilege'])[1]/following::button[1]</value>
      <webElementGuid>e8c32505-7077-412a-90f8-8205fe58cb17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master'])[1]/following::button[2]</value>
      <webElementGuid>c05fd82c-a740-4079-9ccb-f277dd0cc602</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='s'])[1]/preceding::button[2]</value>
      <webElementGuid>f61e7689-e48f-4d8a-87b1-c777f7d56190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[8]</value>
      <webElementGuid>ff7951fe-b50b-42ef-b53b-8c52e99585be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Stock Management Tool' or . = 'Stock Management Tool')]</value>
      <webElementGuid>3174af73-468f-4b47-ad6d-86a186da090d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
