<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>S1_TC088-TC096</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>3dc2ff90-2148-4ed5-9618-a111e1856946</testSuiteGuid>
   <testCaseLink>
      <guid>fbedfd1e-7462-4a2d-89cc-e56a96e51710</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC088-Supplier1 Approve and Release Seller GI Invoice</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>415a8ed5-3bdd-400e-8bcd-dc6eb12ff56f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5fb94cb6-ed4b-415a-a15a-68eba2539365</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>89a0cc85-12b7-49dd-bc0b-b6409d56edab</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC089-BU3 Auto Generate Buyer GR Invoice</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>45a95c4b-f94e-4572-a4bf-b8aaca6197f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5fb94cb6-ed4b-415a-a15a-68eba2539365</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>20c234ba-8ae7-4cb7-a901-cf66148c7257</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC090-Supplier1 Revise and Confirm Shipping Detail</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76dd0665-06d8-4e74-8d39-85e2b8662ef9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a99a9917-5fd1-4d1b-8788-7ce6d540c514</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2d06aa8a-0da2-49a7-adbc-ae81775537b3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC091-BU3 Check Shipping Detail after Supplier1 Confirm Shipment</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6a22d72-350c-451b-a192-1e5677592dd7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3106d671-3165-48d2-9dbe-8d6ff926c468</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC092-DC3 Check Shipping Detail after Supplier1 Confirm Shipment</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed0593d0-031b-4611-9c6f-6718c131e55c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a02c9446-729e-48f5-a22c-54ebc1d4c85f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC093-Customer Check Cargo Tracking Detail after Supplier1 Update and Confirm Shipment</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8da2e52-9ea5-4387-a495-c93e750006f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>288eaa43-b566-4785-bd8e-07dab0bc81fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0631491-0fa3-4c10-8702-10f6e26398f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afdc6236-3933-40d5-8c76-b48fa204b50d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9a084a54-51e3-45b6-a1fe-5e27cd2fd171</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC094-BU1 Check Cargo Tracking Detail after Supplier1 Update and Confirm Shipment</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5e486d1-25b3-43e5-8923-36fa49f6c18c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>288eaa43-b566-4785-bd8e-07dab0bc81fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0631491-0fa3-4c10-8702-10f6e26398f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afdc6236-3933-40d5-8c76-b48fa204b50d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>974d2eca-138a-43ae-9792-74f139e3c8ed</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC095-BU3 Check Cargo Tracking Detail after Supplier1 Update and Confirm Shipment</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60b3c1d2-e09e-4c33-9ef1-8ffd951f4dfe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>288eaa43-b566-4785-bd8e-07dab0bc81fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0631491-0fa3-4c10-8702-10f6e26398f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afdc6236-3933-40d5-8c76-b48fa204b50d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>efaf3ddd-433f-410c-aa75-847a066ed2b6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC096-Supplier1 Check Cargo Tracking Detail after Supplier1 Update and Confirm Shipment</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b26cf35-9e43-4fb5-868e-dfad921b3574</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>288eaa43-b566-4785-bd8e-07dab0bc81fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0631491-0fa3-4c10-8702-10f6e26398f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afdc6236-3933-40d5-8c76-b48fa204b50d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
