<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>S1_TC039-TC045</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>838492fd-bc41-415a-858f-585cb72ac353</testSuiteGuid>
   <testCaseLink>
      <guid>177c0272-0e30-4ee6-b05f-4669fa758d42</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC039-Sup2 Check Sales Order -Received</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a40d264-9653-4c60-a7ff-c205e230edb4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d2d93b0-b063-4690-85c9-b23816c4d9b5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d1014ff9-8c43-45f4-bdf1-7e47709ea7a8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC040-Sup1 Check Sales Order -Cancelled</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7599d98a-c0b8-4467-95f9-de1b3a845656</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba230906-f8da-4849-8d0b-0ed247bcfbdb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e918989f-5cb1-4837-bba2-d4f7c6406384</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC041-BU3 Check Purchase Order -Cancelled</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b87ea00f-fc02-428d-a83e-c9c2968a2364</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8fb115a3-ed0e-4f88-97bb-81719c2088f4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0d619943-1aea-45a7-936f-fc00b22923ba</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC042-BU3 Check Sales Order -Cancelled</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b5cbd7b-989b-464e-90f4-69fb0595a15c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>356b513c-f851-4f84-afed-7aec6e4d0c64</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>869cb197-960f-4fbd-a390-fe58cc933578</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC043-BU1 Check Purchase Order</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a8956a5-60c5-4dfc-9534-203b16fe9848</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03a1ec61-f28c-4d73-8604-8c1e02cc562a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5619434a-4a94-474c-a057-fa5440a90d86</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f647ff8b-7d4f-41bf-a20d-0e97d6695e30</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC044-BU1 Check Sales Order</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ddc4facf-201f-452a-955d-f0d17accb318</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc56a566-4c8d-44ab-bef5-cd3bb6af9234</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5619434a-4a94-474c-a057-fa5440a90d86</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebe316c5-0ba4-4b9f-829a-7fb4ab4d02ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17c2282d-a62b-49e3-9af4-10a4f32c1bb6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8b04bff-2e61-4995-8908-602c192646cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>504e7f25-49d3-4b7c-944b-a7c2bb9f4629</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d9d522e0-283e-476a-a975-6ba0482b1181</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC045-Customer Check Customer Order</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d84afbf-754e-4820-a69e-6b2631aed3f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8be578cb-a6dc-4014-9038-8c08aedfb1c6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41654a2f-4bc1-4614-8960-bf66af6ea5f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2bf2c0e8-acdb-4928-b6aa-59f69f28858a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17c2282d-a62b-49e3-9af4-10a4f32c1bb6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e11ebb7c-e5df-49a9-8c41-374c1503ab95</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
