<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>S1_TC193-TC197</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>278f0374-8a83-4d63-b3f1-b9613f742dd4</testSuiteGuid>
   <testCaseLink>
      <guid>f19219fd-c276-4118-88be-a4db31187c76</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC193-BU2 Check Sales Order after DC1 Inbound</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>00f9bd7b-fb7d-454d-88c3-073beb9888fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a8af89a-efd6-4851-8b91-5d6653a0613d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2985a930-0f88-4c2e-ac15-f9967cdd3299</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>48b92d50-a4a9-4939-80d0-a2dc3f4288aa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC194-BU1 Check Purchase Order BU1 after DC1 Inbound</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6f2a601-06b0-4c94-a7f3-9e0e99f84e62</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c16a12be-fc96-4cf4-ac03-745428f52181</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c1c1a92-2353-45bc-80a6-76c4545e2bcd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>701a5c84-fa02-4100-82e3-cbf52b9cf990</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC195-BU1 Check Sales Order after DC1 Inbound</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>49710f18-0500-458a-8e8e-ce540d6df800</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>baa99489-8e59-4251-bd62-7377c974b9cb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f35b7c59-b7ae-417e-83ea-d8729404bca5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ee92446c-6448-4c25-afe7-6a9d0769da79</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC196-Customer Check Customer Order after DC1 Inbound</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>552b10d6-6303-4d42-a9dd-151066378e30</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bb07757d-1f08-4d05-b5bb-45c6ea3c576d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bbb16d50-d988-462e-aaee-a328d13a5575</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>668e3279-d6bf-4103-9ef6-379e2f4c7bb9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC197-DC1 Update Shipping Detail</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4fbd486a-0aef-4109-b814-7f59a8afaa33</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>21457a89-eaa6-4fb8-afde-7171f40b6185</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
