<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>S1_TC060-TC072</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>ac6978a4-e552-49d8-86a8-ee775009ec51</testSuiteGuid>
   <testCaseLink>
      <guid>5b7ba42b-101e-4c54-933f-7c5a896bdb54</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC060-Customer Reject Change Request from Supplier1</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1768104-d3e3-4585-9a17-d9861b6891cb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b9a02d5-3a51-40ca-8fba-51b11222783f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>177604a5-42b7-460f-b270-d691c588f1c1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8168fa48-3342-4627-824c-35a75884ace8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC061-Customer Approve Change Request from Supplier2</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>475f77ab-5ec5-4b6f-9bec-daec3fa809b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bef1b324-4c91-4a16-bbfb-5c17bff05373</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b9a02d5-3a51-40ca-8fba-51b11222783f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>177604a5-42b7-460f-b270-d691c588f1c1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fb13a31f-577f-4c25-94c6-f31961d822da</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC062-BU1 Check ChangeCancel Request</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1228ea7e-4098-4371-8401-9a0947ffd4e2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1228ea7e-4098-4371-8401-9a0947ffd4e2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>170941d3-8ab3-4e44-84e1-8ab6f626a9e9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cead6d6f-256f-43bb-b065-cdf05fd6829a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC063-BU2 Check Change Request</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d49545a-d6ef-41b8-866b-fec311659603</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ecb51b2a-58da-4b69-b5bf-8c80899f817d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a8ab147a-fd44-4d34-a593-496b18e643de</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC064-BU3 Check Cancel Request</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96e6abe7-008b-45d4-ab59-48c30c1cee12</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85975bb3-4de3-423b-9877-0a3a25979eab</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>47d37d06-f774-4eba-b5b9-62af3c93ba8b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC065-Supplier1 Check Cancel Request</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5cede8b-b2fe-424a-8fdf-c95b3d40eaa8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d94c9170-c027-4af4-a1d3-ad760700d3a0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>35ee18b7-73c3-4f39-86dd-0d356e8fd1e0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC066-Supplier2 Check Change Request</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d7189f7-3231-4dfa-afab-5ff400131c13</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9d851af-e89b-40c2-9c3a-9e1e45908168</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9cb1f56a-0a5b-4181-97ac-65e2244484b0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC067-Supplier2 Check Sales Order</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af2c4f3d-b3f6-4a22-9c40-f31610a79c26</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b93ec78-b6a1-4213-abac-a551766013fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3fccbba-f6cd-4ca7-8359-ec97307d7af3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02be95f5-3b86-4e30-9621-bd35dd15fc0b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a9b0f102-09cc-44ea-8de5-68915851e6b4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2a1f4343-ad47-461b-9ede-8c0f2b30f318</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC068-BU2 Check Purchase Order</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>583e3bae-c693-4f23-8832-7ffe0a5720b4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6072b291-99c6-4a25-8e84-2281f3b6ced7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5776b556-e189-42cb-b02f-89060ac8114f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46d94e51-f1bc-496b-b019-7cade601da91</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a898b6c-f0fd-4846-a34d-62324075a4c5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>488d5c02-b490-4ac4-9a4c-d20e2e1a98e1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC069-BU2 Check Sales Order</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9c2c7ca-4b1c-434c-a68f-a2c32556705e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c0c32e2-5037-4fe9-9cf4-4eb23eca3c4b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b134393-af51-47e2-9806-061464a533ad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>810a2f9d-6cbc-43c0-ad7d-912d51e89e99</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>271539a4-ba51-41e9-bb78-cbae2c0bd441</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3b0da408-9321-407a-b8d2-19618273575e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC070-BU1 Check Purchase Order</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b5adaf7-7926-4409-95a5-055ee159bd99</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4aff16da-c10e-401b-94ce-366232b69a94</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>77753fc7-164e-464b-a69a-287cdd8fc53f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee13c36d-8c74-45ed-9f3f-182a189f5ba3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84a87c34-05d0-4f2b-ad6a-d4e99da8339a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>31061690-6429-4f35-9e1e-f1a428346dd0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC071-BU1 Check Sales Order</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>627c81ad-e4d3-4e09-b28f-a5092a09f6e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>206b835a-58a6-4f46-96fe-8a76635507ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68d08257-d6af-4eda-9a50-17f31ce5c04d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75ce616b-f525-40fe-a30f-f0564cd0b5d6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6bf21b31-7ef7-43c7-b1f4-56ddee72be34</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28eb18c3-2009-4991-bdd5-cc04351b5452</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62c2a61f-2401-4b81-a993-f84a06f85298</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5ead1649-a602-49c3-8020-7b538f95a917</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC072-Cus Check Sales Order</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>669e620b-990a-4390-9a0b-42a066a89f23</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3c47be8-fdb3-4ade-84fd-b2e499840fd7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bb6140f4-1aae-409d-81a4-3dfab479e97d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef470615-6173-458e-8df4-9ed3cc430acd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>694ab6cb-5939-4ffd-bb3a-82763eec6995</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0acf0fa2-37b3-4dfa-a3ab-49266532809d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>89527de0-9ca4-49c3-8092-8ed2c492e4c7</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
