<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>S1_TC053-TC059</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>f520f3e0-b78c-47e6-a506-9699bea652da</testSuiteGuid>
   <testCaseLink>
      <guid>05545e25-c853-4022-912e-d19b320f5efb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC053- Sup1 Cancel Order</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6854118-2719-4391-ade6-b03ef6c18fa2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b32d9f3f-84d8-4f85-8d45-c61a96651b37</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC054-Create Supplier Order Change from SO Monitoring Detail</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8ea0e61-3679-48c6-b092-20a3a551b84a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>983009c2-09eb-4781-9cfa-7adae073a9b4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1bee9d3a-03e9-4384-8afa-ed4fb069ccc1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e94c8a59-fbaf-417b-875d-f579f488dc19</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94799cbf-b2be-44d2-ad66-8d876660ad3d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3fb33fad-6b2b-4bf3-bd44-1b4b54505d8e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8304d648-d46d-4ca0-a5d6-56d8f09f6aab</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>11ac25bf-d962-44ad-ba20-e6f270567e9a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC055-BU3 Auto Generate Cancel Request</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a951bcc3-21f2-4998-8b96-b5e6df3e16e7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6623fb4a-9d72-4cdf-8d70-1c7aa9646bd8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>177efa01-d1ac-4158-bc8e-fe53482537a3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC056-BU2 Auto Generate Change Request</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>838568ea-e3cc-4f28-8b01-2dd901aa496a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>155f30c3-edbb-45cf-9041-56aa31882b18</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f9c249cd-292a-4264-b413-8ef38eb5d7b0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC057-BU1 Auto Generate ChangeCancel Request</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3b94457-1b11-4b66-b5c1-55d721e00400</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f390ea02-bfc5-4dad-9593-e9b6c8752c96</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f5e6fff-52ab-4f0c-902f-ac45872cadc3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>12a3d575-1718-4fe9-b9df-afbe6d8ced40</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC058-Customer Auto Generate To Do Task</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3b94457-1b11-4b66-b5c1-55d721e00400</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f390ea02-bfc5-4dad-9593-e9b6c8752c96</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>46ca41e7-9d15-4238-b8d9-b558f5803f5a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC059- Customer Auto Generate Mail Task</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b007aba-a35c-485e-a1fa-8493046f0ebb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f93873fc-99d6-448f-b8b9-3c0b9a806631</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
