<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>S1_TC132-TC141</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>9c7ad3f8-79de-4b6a-a173-aab377274ece</testSuiteGuid>
   <testCaseLink>
      <guid>6e1d53e5-a70d-4aa3-985f-c22c4dfb494b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC132-BU3 Revise and Approve Seller GI Invoice</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15256da2-9a39-47a4-ae2f-29cddca6b618</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c8c3f36-a96e-4705-bafc-5bc0e9104d2f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cd559722-7d03-462b-9f9e-0e19c3260dec</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC133-BU3 Auto Generate Custom Invoice -Export</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5fc5e409-d2da-408f-b4aa-1f680b42fed0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b83dfd36-9957-4984-ab4d-a2a9f4f14e5e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC134-BU1 Auto Generate Custom Invoice -Import</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5fc5e409-d2da-408f-b4aa-1f680b42fed0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>88aa521b-ab47-4d42-a1de-ccedf3982b7f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC136-BU3 Check Cargo Tracking Detail after Complete Custom Invoice -Export</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0100d215-d782-4ef1-b309-3cc4d9de6883</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca79ed0d-dd1f-4f3a-9f5e-4785ed9a1709</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0cccb0f-8276-47c7-9675-1b131d790e6d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13386429-fd90-4fba-91a1-d7f120aa44d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc4dd976-fcf0-4157-bf4d-14f32c439aa1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>01eb0cc4-a6e1-4e52-b478-9c033ae71053</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC137-BU1 Complete Custom Invoice -Import</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5fc5e409-d2da-408f-b4aa-1f680b42fed0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>63ac890b-16aa-415b-88e2-a153a17aa9dc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC138-BU1 Check Cargo Tracking Detail after Complete Custom Invoice -Import</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc739cbe-29d2-4b18-adde-f1b234ee4df1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>00a29b22-bb3e-4fa5-813f-2dcc84479fee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea4e7912-cfa2-4d11-b7f4-2d51ba1b380e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af408ebb-0c67-4d76-b325-1575eb706a8a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15cc3dbb-a17f-4e9c-a7a4-ea2c84bd3f14</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>102b56a2-54bc-49e3-a7b4-6d2035ec3657</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC139-BU3 Release SellerGI Invoice</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5fc5e409-d2da-408f-b4aa-1f680b42fed0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>635de136-d167-40ef-8bed-53dcb3955da0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenario 1/S1_TC140-BU1 Auto Generate BuyerGR Invoice</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5fc5e409-d2da-408f-b4aa-1f680b42fed0</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
