<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_deliveryTo</name>
   <tag></tag>
   <elementGuidId>5eb540f7-600b-4cf3-91b7-8bc1ad2e0aba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-45473-option-9</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '${deliveryTo}' or . = '${deliveryTo}')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='mui-45473-option-9']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>a7d962a8-f7a1-4561-ac82-4df05d58e68f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d9e32eff-ba7c-4e3e-aad3-5da9b2cb000e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>bc77bd39-4a44-4d9a-afbf-add6bf0d4b99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-45473-option-9</value>
      <webElementGuid>2c2959b7-d84d-42a6-ae9e-9bc61c84a171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>f0840b5a-9c56-4868-a968-f95c774e444e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>715e7488-81eb-4666-a562-15bc7a5527df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>956a756a-fb37-4615-bc4f-ad0ea189f5db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lcbm-MuiAutocomplete-option</value>
      <webElementGuid>f13a5dae-7d97-4914-81e8-f603e4233dce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focus</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2e0508df-2d18-4191-be7f-de82c0987639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${deliveryTo}</value>
      <webElementGuid>192b4895-e020-4fb9-a18f-7dabb29f6761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-45473-option-9&quot;)</value>
      <webElementGuid>2fc78c12-949e-40c8-80f9-587e3926c0df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='mui-45473-option-9']</value>
      <webElementGuid>cf6556d5-5257-43b7-85ca-ebf49cda478d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='mui-45473-popup']/li[10]</value>
      <webElementGuid>1d53b9e8-6dc6-4c28-ba60-ed9fde06e7c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PK-CUS-001'])[1]/following::li[1]</value>
      <webElementGuid>c763e415-e64d-46f3-9949-c311274e1983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PK-CUS'])[1]/following::li[2]</value>
      <webElementGuid>3d318d56-5850-47af-817c-28a6b09bddd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PK-CUS-POC'])[1]/preceding::li[1]</value>
      <webElementGuid>b563bc81-4c82-4a1d-b259-6c11bbc0c4df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PKDC'])[1]/preceding::li[2]</value>
      <webElementGuid>889ceeda-c0e1-4c64-87ee-3f9d18b627f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PK-CUS-DC']/parent::*</value>
      <webElementGuid>6a039a82-c92e-46ac-be93-4b9cd2fae6c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[10]</value>
      <webElementGuid>772bf0c2-affd-48b4-8302-16947a3d90eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'mui-45473-option-9' and (text() = 'PK-CUS-DC' or . = 'PK-CUS-DC')]</value>
      <webElementGuid>74244316-7e8e-4c41-8389-b938d0930c60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
