<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Download</name>
   <tag></tag>
   <elementGuidId>72c95ba0-8165-4fed-a7fd-700557e54c74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ItemDownloaderfc0412985e57']/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.item-downloader__button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Download' or . = 'Download')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>05e95a3d-5c2f-474c-ab31-6b79313e009f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://s-win1.freeconvert.com/task/6527be8cb44640cd09782152/s5%20TC029%20Daily%20Rundown.20231012152949.xlsx</value>
      <webElementGuid>d92fa231-d3dc-44ad-a190-6341d9eabd3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>ItemDownloadButton</value>
      <webElementGuid>79de3de2-c691-436f-b38b-7d5ae21ca4c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>85cad147-beb3-4bc3-a8e9-51ba495e06c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn item-downloader__button</value>
      <webElementGuid>41141948-72dc-42d4-8037-4abd54a2cf6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Download</value>
      <webElementGuid>705e7308-fbf3-4baf-b1c3-16f01734a160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ItemDownloaderfc0412985e57&quot;)/div[@class=&quot;btn-group item-downloader__button-group v-popper--has-tooltip&quot;]/a[@class=&quot;btn item-downloader__button&quot;]</value>
      <webElementGuid>25f1c6fa-c4f3-4555-85c3-84d84a51b74a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ItemDownloaderfc0412985e57']/div/a</value>
      <webElementGuid>464fdb12-76d0-45a9-ba14-d9a5c936771a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Download')]</value>
      <webElementGuid>29f8130a-ac3f-48e1-9b75-b39412e25a6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Done'])[1]/following::a[1]</value>
      <webElementGuid>9cdcfa46-3e9c-48ea-8005-27ff65bc7e7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='s5 TC029 Daily ...1012152949.xlsm'])[1]/following::a[1]</value>
      <webElementGuid>67744ddb-c086-41e9-a705-344b051be6ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Convert More'])[1]/preceding::a[1]</value>
      <webElementGuid>45246ad3-5076-4592-8dae-5ecdbc777a8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you a happy user?'])[1]/preceding::a[2]</value>
      <webElementGuid>34d9f7a0-41bd-4f1d-a32a-99d51047c5ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Download']/parent::*</value>
      <webElementGuid>fe4a27be-b6c5-4258-bb7a-7822e9cac8bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://s-win1.freeconvert.com/task/6527be8cb44640cd09782152/s5%20TC029%20Daily%20Rundown.20231012152949.xlsx')]</value>
      <webElementGuid>2ba5426a-f99c-42d8-84f1-e1f5ad1b8844</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/div/div/a</value>
      <webElementGuid>394604f7-ebfb-4e61-929a-0f49d5833870</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://s-win1.freeconvert.com/task/6527be8cb44640cd09782152/s5%20TC029%20Daily%20Rundown.20231012152949.xlsx' and (text() = 'Download' or . = 'Download')]</value>
      <webElementGuid>97b5ba76-7c22-4746-b993-1e0988574cbc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
