<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_NotiMsg_BatchCombineOrder_Success</name>
   <tag></tag>
   <elementGuidId>b1979dd0-cbc7-48d8-b1f9-7aa668d404d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.base-MuiAlert-message</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'Combine Order.The operation was successful.' or . = 'Combine Order.The operation was successful.')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9758bc7e-e7d8-45a0-8b18-567470bd139f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>base-MuiAlert-message</value>
      <webElementGuid>f4319ae5-aa88-42f6-ae1d-cc49954fbdeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Combine Order.The operation was successful.</value>
      <webElementGuid>23cca6fb-b06c-4915-8f0e-a2efabf78658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;webapp-base&quot;)/div[@class=&quot;base-base1 base-base3 base-base5&quot;]/div[@class=&quot;base-MuiPaper-root base-MuiAlert-root base-MuiAlert-standardSuccess base-base50 base-MuiPaper-elevation0&quot;]/div[@class=&quot;base-MuiAlert-message&quot;]</value>
      <webElementGuid>d1701e8f-020f-41f9-808a-7e196b1db47b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='webapp-base']/div[2]/div/div</value>
      <webElementGuid>583c46ec-e73a-41d8-9d4c-d7b06ffb5fad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='a'])[1]/following::div[4]</value>
      <webElementGuid>65ced27f-9649-44ff-a756-557a949f2e5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stock Management Tool'])[1]/following::div[8]</value>
      <webElementGuid>cee9e701-f271-48b6-90c8-ab3c6c6e4641</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/preceding::div[24]</value>
      <webElementGuid>108fba61-984f-4b6c-9ca9-756f6d18b6a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div</value>
      <webElementGuid>ddff156b-1c56-43c2-86a7-2d7692a1dad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Combine Order.The operation was successful.' or . = 'Combine Order.The operation was successful.')]</value>
      <webElementGuid>51879ecf-0d51-4552-ac01-bd82862e6412</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
