<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_NotiMsg_DwnloadCustOrderbyExcel_Success</name>
   <tag></tag>
   <elementGuidId>6daf8ccf-996c-4980-b3f1-55d5062ab1a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'The operation was successful.' or . = 'The operation was successful.')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'Download Customer Order by Excel.The operation was successful.' or . = 'Download Customer Order by Excel.The operation was successful.')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.base-MuiAlert-message</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ab20481e-5180-4eba-9d5d-36ce3dcf9a2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>base-MuiAlert-message</value>
      <webElementGuid>98131b77-e40d-4701-b676-ea9002f77d5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The operation was successful.</value>
      <webElementGuid>31bce7e7-39c2-4fcc-b758-eaa82f082ac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;webapp-base&quot;)/div[@class=&quot;base-base1 base-base3 base-base5&quot;]/div[@class=&quot;base-MuiPaper-root base-MuiAlert-root base-MuiAlert-standardSuccess base-base60 base-MuiPaper-elevation0&quot;]/div[@class=&quot;base-MuiAlert-message&quot;]</value>
      <webElementGuid>40e3b870-b0be-46ee-975c-ff8031a3a79f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='webapp-base']/div[2]/div/div</value>
      <webElementGuid>61631153-704b-421a-bcb2-4c2d86626bdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='u'])[1]/following::div[4]</value>
      <webElementGuid>8144a528-da44-466f-bd55-f0ea25598ddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stock Management Tool'])[1]/following::div[8]</value>
      <webElementGuid>8d1c4227-c51e-4fe0-a377-e7bc2a666cab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/preceding::div[24]</value>
      <webElementGuid>17b2d9c7-5503-4ba7-9790-a835a32f2f0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div</value>
      <webElementGuid>11907974-8d91-4323-aeaa-41e9bd1d6410</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Download Customer Order by Excel.The operation was successful.' or . = 'Download Customer Order by Excel.The operation was successful.')]</value>
      <webElementGuid>463ef3c8-8473-4a69-b097-1c86948663f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
