<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_NotiMsg_UploadCommonMaster_Successful</name>
   <tag></tag>
   <elementGuidId>07e9ebf8-73ca-440b-aea4-38ee0e427139</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[(contains(text(), 'Upload ${commonOption} Master.The operation was successful.') or contains(., 'Upload ${commonOption} Master.The operation was successful.'))]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(., 'Upload') and contains(., '${uploadOption}') and contains(., 'The operation was successful.')]
</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.base-MuiAlert-message</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4f08a025-da84-4ac4-b547-669db84a2b81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>base-MuiAlert-message</value>
      <webElementGuid>1f3096b5-58ff-4ce4-86d1-8b061a95932e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Upload ${commonOption} Master.The operation was successful.</value>
      <webElementGuid>94fdd3b5-20e5-4cdc-8bb9-e65fd9bb1deb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;webapp-base&quot;)/div[@class=&quot;base-base25 base-base27 base-base29&quot;]/div[@class=&quot;base-MuiPaper-root base-MuiAlert-root base-MuiAlert-standardSuccess base-base93 base-MuiPaper-elevation0&quot;]/div[@class=&quot;base-MuiAlert-message&quot;]</value>
      <webElementGuid>d31cc09e-7173-4535-a027-df01aa541265</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='webapp-base']/div[2]/div/div</value>
      <webElementGuid>eace8ff5-e45c-4d1c-a275-7bca37233a37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='a'])[1]/following::div[4]</value>
      <webElementGuid>3404d258-0eef-42d5-acbb-240a751a5509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stock Management Tool'])[1]/following::div[8]</value>
      <webElementGuid>afcf92e8-170f-464b-be81-6a4d0b46c7d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/preceding::div[24]</value>
      <webElementGuid>098d3ae8-b285-47c5-80e8-e3514a36ac14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div</value>
      <webElementGuid>3f38cd14-764e-4786-bff7-cbb4ef0ac05b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Upload Region Master.The operation was successful.' or . = 'Upload Region Master.The operation was successful.')]</value>
      <webElementGuid>6b2bd90a-1698-4c94-b4dd-4cb66f9b467a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
