<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_orderPeriod</name>
   <tag></tag>
   <elementGuidId>634d547f-d89b-4235-8075-7f9b21f838e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[(text() = '${WeeklyPeriod}' or . = '${WeeklyPeriod}')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mui-38962-option-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='mui-38962-option-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>cf069a67-98ab-426e-be44-af4adc5c9827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>c96f29b3-1c28-4fce-be39-cfeb74ad98fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>9a32e64c-f8c4-4127-b592-c795a6eb7099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-38962-option-3</value>
      <webElementGuid>ed919b32-62d5-431d-8b0d-355f261ea36c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>79c2764d-9078-4b28-aae0-4b73e9840ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b4f98dc1-a0da-4728-807b-2f4c3549f90e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d1438e29-5b19-4b14-bd56-22a5faaadfbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lcbm-MuiAutocomplete-option</value>
      <webElementGuid>6a2d8382-0484-48a4-8f16-4003855a4552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focus</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d452a41a-9af2-4d4e-9a36-6977f4edfe41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${WeeklyPeriod}</value>
      <webElementGuid>8e06c6cd-53ee-48ed-8e43-3b8de3ffb888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-38962-option-3&quot;)</value>
      <webElementGuid>2b6dc6e2-0d5b-4b07-951a-7ed6775814b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='mui-38962-option-3']</value>
      <webElementGuid>638e5b6a-7862-4a68-9a37-435b85a977cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='mui-38962-popup']/li[4]</value>
      <webElementGuid>375c8a9c-e390-4112-b585-7cb0f3809cd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oct 2, 2023 ~ Oct 8, 2023'])[1]/following::li[1]</value>
      <webElementGuid>4daee093-8f68-42f6-b531-07232516664a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sep 25, 2023 ~ Oct 1, 2023'])[1]/following::li[2]</value>
      <webElementGuid>27783897-748b-407d-b3af-cc9176e52b0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oct 16, 2023 ~ Oct 22, 2023'])[1]/preceding::li[1]</value>
      <webElementGuid>ddaa750b-c4fa-421f-a6db-e37204c1b4a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oct 23, 2023 ~ Oct 29, 2023'])[1]/preceding::li[2]</value>
      <webElementGuid>b9742c4b-48bc-4af9-b0a5-c94e965e3378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]</value>
      <webElementGuid>8df416fb-7ea6-4643-b6e2-c0d8fc6b18c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'mui-38962-option-3' and (text() = 'Oct 9, 2023 ~ Oct 15, 2023' or . = 'Oct 9, 2023 ~ Oct 15, 2023')]</value>
      <webElementGuid>705282da-2c83-48dd-a726-65a6018032ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
