<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_luqman-baf</name>
   <tag></tag>
   <elementGuidId>f4c739cf-965b-4aed-9273-5f280b0dd33f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#base_user_name_label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='base_user_name_label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>33d41466-3510-4df0-aad8-7a52c85f9ccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>base-MuiTypography-root base-base36 base-MuiTypography-body1 base-MuiTypography-colorTextPrimary</value>
      <webElementGuid>f610c127-0dd2-4d36-9181-65dec9419e05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>base_user_name_label</value>
      <webElementGuid>48a29a5d-82a1-4db0-8a69-e3ac518ec57f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>luqman-baf</value>
      <webElementGuid>d1c283f9-ac91-45f5-91fb-ae8c9eac5f1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;base_user_name_label&quot;)</value>
      <webElementGuid>fab78324-fbc8-48d6-aa4c-63f608dccabf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='base_user_name_label']</value>
      <webElementGuid>95764e83-1327-4038-a3a9-5360e14cab77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='Base_Workbench_UserProfile_Button']/span/div/div[2]/p[2]</value>
      <webElementGuid>e46654bd-c95a-4a43-8fc4-e8aa6b93fc2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='l'])[1]/following::p[2]</value>
      <webElementGuid>a46a8bd3-2005-4253-a7d7-fd18c1cb420f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privilege'])[1]/following::p[2]</value>
      <webElementGuid>f902379b-26de-4532-bb87-7aab88330a22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/preceding::p[1]</value>
      <webElementGuid>1309a351-2da6-4177-92ce-5ac338d3f3bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'base_user_name_label', '&quot;', ')')])[1]/preceding::p[1]</value>
      <webElementGuid>7aeb5c0a-6744-4add-a9fd-5d34157afe1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p[2]</value>
      <webElementGuid>6eb42be6-7489-4fd8-981c-c0aacd54247c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'base_user_name_label' and (text() = 'luqman-baf' or . = 'luqman-baf')]</value>
      <webElementGuid>8c9c1552-b05d-4235-9279-1450d5876375</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
