<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_contractRoute</name>
   <tag></tag>
   <elementGuidId>faca9f56-a72d-4908-97e4-2b55dd8a695b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-17528-option-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[(text() = '${contractRouteCode}' or . = '${contractRouteCode}')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '${contractRouteCode}' or . = '${contractRouteCode}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>ca8dbaa1-ae19-4f48-991e-d51762e70d99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d3918f3c-6c47-444e-89d8-80edbb529def</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>b92e98b6-14cb-4736-ac6b-b01073f6c766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-17528-option-1</value>
      <webElementGuid>b67e46da-e1a1-4b7e-8722-ce1385107a45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5ece43ce-ef77-4c92-9769-b93c977d3ec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4aa568d7-64fe-42f2-9b5e-26d33ba6f9c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e0695f93-0cd3-4b21-8932-a64e47d68f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lcbm-MuiAutocomplete-option</value>
      <webElementGuid>abdbe2aa-db94-4ee8-9988-70fa6299e850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focus</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>74333355-2516-415e-ac27-8a8425895497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${contractRouteCode}</value>
      <webElementGuid>232d6d17-02d7-4191-8a39-0052e1de5bc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-17528-option-1&quot;)</value>
      <webElementGuid>19cb446a-07f8-48b0-a5a4-acfd884099af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='mui-17528-option-1']</value>
      <webElementGuid>2bc0f16c-7e1d-4a12-89ca-9184cfaa37a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='mui-17528-popup']/li[2]</value>
      <webElementGuid>bd65ecac-eac0-44cb-871a-46c4b70181da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CR-VN-TTVN-2308001'])[1]/following::li[1]</value>
      <webElementGuid>726c1577-429b-470f-b531-d1da97917ced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'mui-17528-option-1', '&quot;', ')')])[1]/following::li[2]</value>
      <webElementGuid>90e55428-64bf-4ab2-a718-cff762f2879d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CR-VN-TTVN-2308002']/parent::*</value>
      <webElementGuid>575c3055-debf-4d03-853b-50f804f15617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/li[2]</value>
      <webElementGuid>19ec938f-8c76-4433-a0f7-72a31e884e36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'mui-17528-option-1' and (text() = 'CR-VN-TTVN-2308002' or . = 'CR-VN-TTVN-2308002')]</value>
      <webElementGuid>fc646bc0-aa01-4601-a43e-5018ca6d4358</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
