<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_contractNo</name>
   <tag></tag>
   <elementGuidId>ef5f40cc-1f95-4201-b4c9-66198b920ea9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-46664-option-6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='mui-46664-option-6']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//li[(text() = '${contract_id}' or . = '${contract_id}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>89a9e62e-68cb-4ac0-bb85-76642fbdd860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>35fd24a2-3156-4509-a35c-47c5b65fe58a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>64a620ce-9089-4234-a1e8-6abec7aa47a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-46664-option-6</value>
      <webElementGuid>c7501df9-55c7-4056-b600-33977b53e508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>a9e27c32-ad00-4dfd-9354-62ddba3702d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fc26193f-54fe-48de-a04c-10ba2b7f61ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>35734c8d-1d7c-4209-b141-375f09ad12ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lcbm-MuiAutocomplete-option</value>
      <webElementGuid>435de2ea-93f9-44c2-aca2-069f3ca27c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focus</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7fdbb87e-052a-444c-be1a-8346f9cd8952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${contract_id}</value>
      <webElementGuid>381b2f7d-1d7b-47ab-900f-0a31313094b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-46664-option-6&quot;)</value>
      <webElementGuid>80a76c05-29d5-46a4-99d3-8ca9d7126668</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='mui-46664-option-6']</value>
      <webElementGuid>b62f3648-199c-48c3-9a35-8eb14ac47148</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='mui-46664-popup']/li[7]</value>
      <webElementGuid>83a0b066-72f8-4bfa-844d-6635a0d71079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SGTTAP-VNTTVN-FB-01-001'])[1]/following::li[1]</value>
      <webElementGuid>bf281578-b639-4a5b-94c8-f1d231056c88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SGBAFCO-SGTTAP-FT-01-001'])[1]/following::li[2]</value>
      <webElementGuid>3af3ef8e-11f3-4efd-aa3e-6f3b06635417</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SGBAFCO-SGTTAP-FBS-01-001']/parent::*</value>
      <webElementGuid>95746e61-c76e-41bc-af4d-ea7c43646bcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]</value>
      <webElementGuid>eaa8c019-10d5-4422-bfbd-124a68813dcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'mui-46664-option-6' and (text() = 'SGBAFCO-SGTTAP-FBS-01-001' or . = 'SGBAFCO-SGTTAP-FBS-01-001')]</value>
      <webElementGuid>b40750fe-682b-40d9-89a5-74b307082f82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
