<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h5_creditlimit</name>
   <tag></tag>
   <elementGuidId>c9f6960c-4d53-451b-bc4a-6ec300299ee7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='webapp-lcbm']/div/div[4]/div/div/div/div/div/div[2]/div/div/div[2]/div/div[5]/div/div/div/div/h5</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.lcbm-lcbm328.lcbm-lcbm340 > div.lcbm-MuiPaper-root.lcbm-MuiCard-root.lcbm-lcbm330.lcbm-MuiPaper-elevation3.lcbm-MuiPaper-rounded > div.lcbm-MuiCardContent-root.lcbm-lcbm331 > div.lcbm-MuiGrid-root.lcbm-MuiGrid-container.lcbm-MuiGrid-spacing-xs-1.lcbm-MuiGrid-align-items-xs-center.lcbm-MuiGrid-align-content-xs-center.lcbm-MuiGrid-justify-content-xs-center > div.lcbm-MuiGrid-root.lcbm-MuiGrid-item > h5.lcbm-MuiTypography-root.lcbm-lcbm332.lcbm-MuiTypography-h5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>e71a8f1e-80a9-4c2c-81e1-8b683a691912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lcbm-MuiTypography-root lcbm-lcbm332 lcbm-MuiTypography-h5</value>
      <webElementGuid>ce919e53-eb03-447f-b87b-80fb49204dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e4b9c33c-a258-46df-b8b1-eedf288d441b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;webapp-lcbm&quot;)/div[@class=&quot;os-host os-host-foreign os-theme-dark os-host-resize-disabled os-host-scrollbar-horizontal-hidden lcbm-lcbm264 os-host-overflow os-host-overflow-y os-host-transition&quot;]/div[@class=&quot;os-padding&quot;]/div[@class=&quot;os-viewport os-viewport-native-scrollbars-invisible&quot;]/div[@class=&quot;os-content&quot;]/div[@class=&quot;lcbm-lcbm265&quot;]/div[@class=&quot;lcbm-lcbm268&quot;]/div[@class=&quot;lcbm-lcbm270&quot;]/div[@class=&quot;lcbm-lcbm276&quot;]/div[@class=&quot;lcbm-lcbm277&quot;]/div[@class=&quot;lcbm-MuiPaper-root lcbm-MuiCard-root lcbm-lcbm318 lcbm-MuiPaper-elevation3 lcbm-MuiPaper-rounded&quot;]/div[@class=&quot;lcbm-lcbm325&quot;]/div[@class=&quot;lcbm-lcbm326 lcbm-lcbm327&quot;]/div[@class=&quot;lcbm-lcbm328 lcbm-lcbm340&quot;]/div[@class=&quot;lcbm-MuiPaper-root lcbm-MuiCard-root lcbm-lcbm330 lcbm-MuiPaper-elevation3 lcbm-MuiPaper-rounded&quot;]/div[@class=&quot;lcbm-MuiCardContent-root lcbm-lcbm331&quot;]/div[@class=&quot;lcbm-MuiGrid-root lcbm-MuiGrid-container lcbm-MuiGrid-spacing-xs-1 lcbm-MuiGrid-align-items-xs-center lcbm-MuiGrid-align-content-xs-center lcbm-MuiGrid-justify-content-xs-center&quot;]/div[@class=&quot;lcbm-MuiGrid-root lcbm-MuiGrid-item&quot;]/h5[@class=&quot;lcbm-MuiTypography-root lcbm-lcbm332 lcbm-MuiTypography-h5&quot;]</value>
      <webElementGuid>c7d0e6a6-91ac-456e-be3c-6bfa91f1b29b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='webapp-lcbm']/div/div[4]/div/div/div/div/div/div[2]/div/div/div[2]/div/div[5]/div/div/div/div/h5</value>
      <webElementGuid>308a2b16-bd14-4bfd-9de5-752c768e7a7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CNY'])[3]/following::h5[1]</value>
      <webElementGuid>c59563e2-09e3-4ae5-bd81-4b342458c471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CNY'])[2]/following::h5[3]</value>
      <webElementGuid>0331cdd5-10fd-4938-a9ae-d0a3141efb20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CNY'])[4]/preceding::h5[1]</value>
      <webElementGuid>f166099e-1eb7-4b44-92ec-adc6dedb3957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OutStanding Amount'])[1]/preceding::h5[2]</value>
      <webElementGuid>abd71c8b-13cd-422d-9859-6daf73007fb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='0']/parent::*</value>
      <webElementGuid>acbe1627-016b-4634-8ed0-19682c3c7150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/h5</value>
      <webElementGuid>82450011-3167-42e3-a2df-2368c4c78760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[(text() = '0' or . = '0')]</value>
      <webElementGuid>e0003c72-df5f-4d1b-8440-a25bfd7c5665</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
