<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_remote_ordertype_Spot</name>
   <tag></tag>
   <elementGuidId>b88f8249-d5e0-45d9-89f2-1cd2a6d9f7c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-40689-option-1</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//li[(text() = 'Spot' or . = 'Spot')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='mui-40689-option-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>006770bb-8334-4d96-816c-ee7df9d35e2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>cca2c700-0681-43c5-9b0b-e0182cac8055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>e97fb143-4dd6-4802-a7f9-6c05aad38820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-40689-option-1</value>
      <webElementGuid>6f755062-b2ca-485b-a201-ab7d8bc7af0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>924ebf93-e565-4d1d-a3f7-1d23ce8bc62f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a1a580cb-3327-4fd7-ab4e-13ed073e0715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>806bb0ef-2584-4d7d-aafd-5534c0aac025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lcbm-MuiAutocomplete-option</value>
      <webElementGuid>ebf50a6b-ec19-4014-a142-ed75baf1c78b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focus</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>19a8e72e-cb56-4c50-bbaa-6b99d62ea419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Spot</value>
      <webElementGuid>f9d11f41-e6d9-48ff-a1c0-8b542e3aad08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-40689-option-1&quot;)</value>
      <webElementGuid>17e3b2f6-34d9-4414-8c35-fbcfa230b983</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='mui-40689-option-1']</value>
      <webElementGuid>2e287215-0c26-437c-85d8-678b5be7c161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='mui-40689-popup']/li[2]</value>
      <webElementGuid>f0107b99-fdc3-4d54-a202-442105a6e15a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regular'])[14]/following::li[1]</value>
      <webElementGuid>dc928956-0c55-4fa1-9b5a-38c1002f6efa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::li[2]</value>
      <webElementGuid>023c30d2-e615-47d5-969f-71dea6e94ae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DI'])[1]/preceding::li[1]</value>
      <webElementGuid>93872c76-8bdc-4f8c-8423-5f61539c4472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spot(without contract)'])[1]/preceding::li[2]</value>
      <webElementGuid>b8a280eb-ebbf-4764-8bef-3f25ab572316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[2]</value>
      <webElementGuid>c4149051-35d4-4557-9652-f0f47e82c3a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'mui-40689-option-1' and (text() = 'Spot' or . = 'Spot')]</value>
      <webElementGuid>9ae2fa3a-5ff6-40ed-9962-0bbef442bd02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
