<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__m3 (Clear)</name>
   <tag></tag>
   <elementGuidId>c254625f-e7c0-4dc6-b02d-e6b8399f9134</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='m3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;m3&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>08a22dc1-d64d-4a88-8879-0c34849bd929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>m3</value>
      <webElementGuid>15befeef-8543-43f5-9315-53c92cabbf84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>da974b98-3df2-4d3f-89e5-4908e2c3f57b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lcbm-MuiInputBase-input lcbm-MuiInput-input</value>
      <webElementGuid>1bddcde7-4071-4b6a-8b74-b3ba340cb8d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>96913590-1314-4545-bfd3-45f8e3864820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;webapp-lcbm&quot;)/div[@class=&quot;os-host os-host-foreign os-theme-dark os-host-resize-disabled os-host-scrollbar-horizontal-hidden lcbm-lcbm7149 os-host-overflow os-host-overflow-y os-host-transition&quot;]/div[@class=&quot;os-padding&quot;]/div[@class=&quot;os-viewport os-viewport-native-scrollbars-invisible&quot;]/div[@class=&quot;os-content&quot;]/div[@class=&quot;lcbm-lcbm7150&quot;]/div[@class=&quot;lcbm-lcbm7155&quot;]/div[@class=&quot;lcbm-MuiPaper-root lcbm-MuiCard-root lcbm-lcbm7582 lcbm-MuiPaper-elevation3 lcbm-MuiPaper-rounded&quot;]/div[@class=&quot;lcbm-lcbm7585&quot;]/form[@class=&quot;lcbm-lcbm8052 lcbm-lcbm8053&quot;]/div[@class=&quot;lcbm-lcbm8054 lcbm-lcbm8093&quot;]/div[@class=&quot;lcbm-lcbm8056&quot;]/div[@class=&quot;lcbm-lcbm8063&quot;]/div[@class=&quot;lcbm-lcbm8069&quot;]/div[@class=&quot;lcbm-lcbm8058&quot;]/div[@class=&quot;lcbm-MuiInputBase-root lcbm-MuiInput-root Mui-focused Mui-focused&quot;]/input[@class=&quot;lcbm-MuiInputBase-input lcbm-MuiInput-input&quot;]</value>
      <webElementGuid>002169a0-8ccb-42b4-ac08-9907bfbe7976</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='m3']</value>
      <webElementGuid>b2c1b7fc-5bae-4f63-933e-192568a35253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='webapp-lcbm']/div/div[4]/div/div/div/div[2]/div/div[2]/form/div[17]/div/div[2]/div/div/div/input</value>
      <webElementGuid>9ea72c2e-dd99-44ba-aee2-de51d8f89940</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div/div[2]/div/div/div/input</value>
      <webElementGuid>073d3324-fa4a-4fc3-8a3d-e24c05da9024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'm3' and @type = 'number']</value>
      <webElementGuid>498b84f3-59a4-4e5a-9e74-1f4d5cf9351f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
