<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__voyageNo</name>
   <tag></tag>
   <elementGuidId>eae58d79-c274-40dd-957d-8babf474edb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='voyageNo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;voyageNo&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c5b3f529-13ed-4a6f-8cb6-a33892891b17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>voyageNo</value>
      <webElementGuid>afe448bc-7147-4313-b9e4-9c8881a1434a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ca637ae7-34e3-46f3-a7d0-aacfa8f43301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lcbm-MuiInputBase-input lcbm-MuiInput-input</value>
      <webElementGuid>d5137d27-4def-48eb-b59c-2b671881c56c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;webapp-lcbm&quot;)/div[@class=&quot;os-host os-host-foreign os-theme-dark os-host-resize-disabled os-host-scrollbar-horizontal-hidden lcbm-lcbm7149 os-host-overflow os-host-overflow-y os-host-transition&quot;]/div[@class=&quot;os-padding&quot;]/div[@class=&quot;os-viewport os-viewport-native-scrollbars-invisible&quot;]/div[@class=&quot;os-content&quot;]/div[@class=&quot;lcbm-lcbm7150&quot;]/div[@class=&quot;lcbm-lcbm7155&quot;]/div[@class=&quot;lcbm-MuiPaper-root lcbm-MuiCard-root lcbm-lcbm7582 lcbm-MuiPaper-elevation3 lcbm-MuiPaper-rounded&quot;]/div[@class=&quot;lcbm-lcbm7585&quot;]/form[@class=&quot;lcbm-lcbm8052 lcbm-lcbm8053&quot;]/div[@class=&quot;lcbm-lcbm8054 lcbm-lcbm8089&quot;]/div[@class=&quot;lcbm-lcbm8056&quot;]/div[@class=&quot;lcbm-lcbm8063&quot;]/div[@class=&quot;lcbm-lcbm8069&quot;]/div[@class=&quot;lcbm-lcbm8058&quot;]/div[@class=&quot;lcbm-MuiInputBase-root lcbm-MuiInput-root Mui-focused Mui-focused&quot;]/input[@class=&quot;lcbm-MuiInputBase-input lcbm-MuiInput-input&quot;]</value>
      <webElementGuid>3c126e51-99fa-4542-80c6-cbd559e40365</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='voyageNo']</value>
      <webElementGuid>a7c79429-c648-4eee-8d73-c4f98bce9dd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='webapp-lcbm']/div/div[4]/div/div/div/div[2]/div/div[2]/form/div[13]/div/div[2]/div/div/div/input</value>
      <webElementGuid>f1d390ca-e0f8-4588-b695-158286ac0dac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div[2]/div/div/div/input</value>
      <webElementGuid>322c963e-e6d6-4e4f-b7d8-11d20782ea14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'voyageNo' and @type = 'text']</value>
      <webElementGuid>60a8a6e3-2a9e-4c3d-bd81-ae381ae40b11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
