<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__adjustmentReason</name>
   <tag></tag>
   <elementGuidId>54e168f1-56e7-4913-aaa9-c3030eb4ca1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;adjustmentReason&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='adjustmentReason']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>423d23da-3d5f-4975-8e1b-8dde4f2e1443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c8c86887-4c14-45a4-87f9-d03b2e7231f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>adjustmentReason</value>
      <webElementGuid>4cfb08a7-784f-4e57-89d9-90101ea8003c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4ad4f728-869b-403b-9983-86e9b9e2a2a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lcbm-MuiInputBase-input lcbm-MuiInput-input</value>
      <webElementGuid>1e9ea649-1787-4a9f-926b-c83d318294c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;lcbm-MuiDialog-root&quot;]/div[@class=&quot;lcbm-MuiDialog-container lcbm-MuiDialog-scrollPaper&quot;]/div[@class=&quot;lcbm-MuiPaper-root lcbm-MuiDialog-paper lcbm-lcbm4028 lcbm-MuiDialog-paperScrollPaper lcbm-MuiDialog-paperWidthSm lcbm-MuiPaper-elevation24 lcbm-MuiPaper-rounded&quot;]/div[@class=&quot;lcbm-MuiDialogContent-root&quot;]/fieldset[@class=&quot;lcbm-MuiFormControl-root&quot;]/div[@class=&quot;lcbm-MuiFormGroup-root&quot;]/form[@class=&quot;lcbm-lcbm4061 lcbm-lcbm4062&quot;]/div[@class=&quot;lcbm-lcbm4063 lcbm-lcbm4064&quot;]/div[@class=&quot;lcbm-lcbm4065&quot;]/div[@class=&quot;lcbm-lcbm4072&quot;]/div[@class=&quot;lcbm-lcbm4078&quot;]/div[@class=&quot;lcbm-lcbm4067&quot;]/div[@class=&quot;lcbm-MuiInputBase-root lcbm-MuiInput-root Mui-focused Mui-focused lcbm-MuiInputBase-formControl lcbm-MuiInput-formControl&quot;]/input[@class=&quot;lcbm-MuiInputBase-input lcbm-MuiInput-input&quot;]</value>
      <webElementGuid>012d13d0-ca33-4a83-8597-3ce363adf112</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='adjustmentReason']</value>
      <webElementGuid>0bef9d10-0bcb-4131-8eec-80a8d4a4772d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>533ade22-ded5-4956-beae-e244e3034847</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'adjustmentReason' and @type = 'text']</value>
      <webElementGuid>2a65d101-7007-4bb1-97bf-ad1c6b759fef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
