<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__mainDescription</name>
   <tag></tag>
   <elementGuidId>8b33985a-b46a-4965-8e93-1fd83d5966fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-53551</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mui-53551']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5b0b7dd0-39f4-4fe8-8a80-6645c8046d8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a4d6427a-9289-4df8-a911-177b6f06e626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mainFieldName</value>
      <webElementGuid>67739ae3-f6df-4cb1-ab7e-b1cc9ec7be7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cdc6b325-4f99-42b2-bbac-24a38faec8e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lcbm-MuiInputBase-input lcbm-MuiInput-input lcbm-MuiAutocomplete-input lcbm-MuiAutocomplete-inputFocused lcbm-MuiInputBase-inputAdornedEnd</value>
      <webElementGuid>19201fe1-bbc4-43bc-862b-f7557a16a2da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>both</value>
      <webElementGuid>850f7458-ed92-4160-95d0-fe6c911f5399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>b4af4a73-ed2b-4253-9122-aeadc873e4cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0fac1f3f-dc61-4e8e-9786-7efba6ddb8c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-53551</value>
      <webElementGuid>6db21249-f308-40c2-9417-b5cf03d81ffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-53551&quot;)</value>
      <webElementGuid>8558e38f-7743-4a83-ad1b-940251558c24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mui-53551']</value>
      <webElementGuid>90b0b087-3a66-4ed8-8a81-cadfccccf7ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='webapp-lcbm']/div/div[4]/div/div/div/div[2]/div[3]/div[2]/div/div/div/form/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>9b82b042-d9cf-4b8a-a033-2939bac32b34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/form/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>f351cf2a-90d8-4c94-82d5-95a461f66406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'mainFieldName' and @type = 'text' and @id = 'mui-53551']</value>
      <webElementGuid>6e67d65c-bcfb-4e03-852f-8c5216d30426</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
