<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Production plan-noOfLevel-Level 2</name>
   <tag></tag>
   <elementGuidId>1a2265dc-4470-479c-9f55-593db979776c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-96218-option-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='mui-96218-option-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>3938cbec-da7b-4b86-b3a5-e278d82c8b9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>eec6e4a5-9e66-4d12-bca4-fdf15c438244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>73a3d0c3-2cd9-4fbd-892b-9c22e808efda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-96218-option-2</value>
      <webElementGuid>95d945a0-9454-4aa3-b2ea-608fce0b58e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>71f11b56-8834-4d5c-9a3a-da66c9f0ba31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6bfeefac-a730-47e7-9f26-c8d268fa6299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c7334dac-68ab-4854-aed2-95c9344a5c1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lcbm-MuiAutocomplete-option</value>
      <webElementGuid>d3519c77-12db-4a88-8588-ad80852ac348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focus</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>21bc278b-0640-4d0b-b16e-1704c119c185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Level 2</value>
      <webElementGuid>5a12259f-e973-44dc-a084-1ce553d1514e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-96218-option-2&quot;)</value>
      <webElementGuid>ee291f8f-def6-4847-9477-b2b560943ee7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='mui-96218-option-2']</value>
      <webElementGuid>674a3fcf-8ed2-4bce-a8fc-554070bd2740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='mui-96218-popup']/li[3]</value>
      <webElementGuid>3ac09ce7-bd06-4093-9c2b-d6e179a561e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Level 1'])[2]/following::li[1]</value>
      <webElementGuid>ac194cd3-2805-4914-a993-ff4481328add</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Final Product'])[1]/following::li[2]</value>
      <webElementGuid>ed0401bc-cd78-43ab-9324-381887975ae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[3]</value>
      <webElementGuid>b0e8252f-9734-459b-a3d3-d92bdd617936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'mui-96218-option-2' and (text() = 'Level 2' or . = 'Level 2')]</value>
      <webElementGuid>320f8261-3f8d-4191-8db4-7376fd48bc82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
