<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Confirm_lcbm-MuiPickersClock-Hour - Copy after 12</name>
   <tag></tag>
   <elementGuidId>9a25e1e3-2ab9-46b6-ba9c-e77bb6263ba8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.lcbm-MuiPickersClock-squareMask</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[1]/div[@class=&quot;lcbm-MuiPopover-root&quot;]/div[@class=&quot;lcbm-MuiPaper-root lcbm-MuiPopover-paper lcbm-lcbm1590 lcbm-MuiPaper-elevation8 lcbm-MuiPaper-rounded&quot;]/div[@class=&quot;lcbm-MuiPickersBasePicker-container&quot;]/div[@class=&quot;lcbm-MuiPickersBasePicker-pickerView&quot;]/div[@class=&quot;lcbm-MuiPickersClock-container&quot;]/div[@class=&quot;lcbm-MuiPickersClock-clock&quot;]/div[@class=&quot;lcbm-MuiPickersClock-squareMask&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@class=&quot;lcbm-MuiTypography-root lcbm-MuiPickersClockNumber-clockNumber lcbm-MuiTypography-body2&quot;][${hour}]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2aa0402b-1a40-4aa2-bfee-a8fe3b8d1ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>2bee1397-077c-4b11-b0b7-1c5333901bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>8607e3ac-c781-4d77-aecf-d882e28ff08b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lcbm-MuiPickersClock-squareMask</value>
      <webElementGuid>7aedd8ae-6b71-4184-ab21-f7427b85367a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;lcbm-MuiPopover-root&quot;]/div[@class=&quot;lcbm-MuiPaper-root lcbm-MuiPopover-paper lcbm-lcbm1590 lcbm-MuiPaper-elevation8 lcbm-MuiPaper-rounded&quot;]/div[@class=&quot;lcbm-MuiPickersBasePicker-container&quot;]/div[@class=&quot;lcbm-MuiPickersBasePicker-pickerView&quot;]/div[@class=&quot;lcbm-MuiPickersClock-container&quot;]/div[@class=&quot;lcbm-MuiPickersClock-clock&quot;]/div[@class=&quot;lcbm-MuiPickersClock-squareMask&quot;]</value>
      <webElementGuid>6aec069d-225c-4eba-8184-cb814ac07316</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div/div/div/div/div</value>
      <webElementGuid>63203a62-d20a-4434-9eaa-fd9c17ac9bd5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
